### ISSUE TITLE
LNUG #70 - 28th Feb 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#1]
Hi all @lnug/organisers and @lnug/contributors  

A lot of new contributors have recently volunteered to contribute and help - so I'm opening up the planning of events so you can all see how we plan things and hopefully get involved with some of the monthly tasks and beyond. 

so... who's going  to be around to help for February?  

Please pick a task or two or three for our next meetup and add your name to it! 

Confirm, ask questions in the comments... 

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github
- [x] Who will emcee this month? 
- [x] Registration - this is all on Meetup now
- [x] Website updates  @admataz
- [x] Monthly Mailer (Mailchimp)
- [x] confirm sponsorship arrangements with Tiro @admataz
- [x] Slides (usually the MC) @clarkie

## Last day checks (Monday before event)
- [x] Confirm with Speakers @clarkie
- [x] Confirm Venue arrangements with Makers @clarkie
- [x] Confirm Video with Pusher @clarkie
- [x] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places] @clarkie
- [x] Pizza orders  @admataz
- [x] Beer orders - @admataz

## On the Night
- [x] MC/host  @clarkie
- [ ] Aris, from CityJSConf - 15 minutes for community talk and promo/ticket raffle
- [x] Ticket Scan/ Door @lazlojuly
- [x] Doors after 7pm - leave a contact number on a note @lazlojuly
- [ ] T-Shirts @admataz
- [x] Twitter and tweeting @claireinez
- [ ] Keep Gitter discussion rolling
- [x] Speakers & AV @lazlojuly @clarkie
- [x] Receive Pizza  @lazlojuly @claudiamatosa 
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) @lazlojuly @claudiamatosa 

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [ ] Stickers 
- [x] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [x] duplicate this list for next month

Anything else?

**Comment by domfarnham** [comment]
Hi Adam,

I can help you with some of this. How do you normally approach the find speakers task? I assume you contact people who have submitted talks to the speakers repo. What do you usually do when you are short and need to find speakers? Do you use social media, is there a list of contacts you approach?

I can also help with making arrangements with Makers, Pusher, etc but will need there contact details.

Dom

**Comment by thanpolas** [comment]
I confirm my speaking engagement, I can make arrangements with vendors or any other logistics you might need, just intro me and give me the goal.

**Comment by admataz** [comment]
hi @domfarnham  and @thanpolas  - thanks for the offers of help - I need to get a few guides to tasks in place to help out - watch this space...  Meanwhile if you are planning to be there on the night - any help with the practical side (@thanpolas you will be busy!)

Meanwhile in answer to your questions about finding future speakers - we rely very much on speakers coming forward with proposals - and adding their proposals to the speakers repo - when we're short, we reach out on twitter and to our networks. When proposals come in I like for more than myself to be looking at them and approving them - so if nothing else, please have a read and contribute any feedback to the speaker - it can really help them shape a good talk.

We have been short of speakers in the past and once had to cancel a planned meetup - and another time managed to get some nice lightning talks together. It would be great if organisers/contributors keep a short talk ready in the case of no speakers or a no-show - it's happened before and turned out to be a fun/fresh evening of talks. 

The job of getting speakers is a long term networking one - so encouraging people you meet to think about telling their story and putting a proposal forward. Also if you ever meet developers with well known projects or modules - it's great to get some well known names in. This year I'd like to see more diversity in the speakers - so encouraging  speakers other than white men should be a real consideration.

**Comment by orliesaurus** [comment]
For the monthly email through MailChimp - what and where do you get the "community" info from?

**Comment by admataz** [comment]
Hi,
It's been a while since I've done it - in the past I've gathered info 
from round and about and people who've sent me info about events on 
meetups etc -  - and also created an issue on github for people to add 
their events/news etc. eg: https://github.com/lnug/feedback/issues/104

A couple events we are supporting with spreading the word...

https://reactfest.com
http://cityjsconf.org
https://amsterdamjs.com


thanks!





-- 
☺ Adam Davis
☞ admataz.com
☏ +44 7757 234443

**Comment by orliesaurus** [comment]
@admataz Who are the sponsors? I got MakersAcedemy Tiropartners and Pusher - Newsletter is ready to be shipped

**Comment by admataz** [comment]
looks good! Sponsors are right... thank-you - you can send when you're ready

**Comment by admataz** [comment]
I've added a todo for the night - we have a ticket to raffle for http://cityjsconf.org

**Comment by clarkie** [comment]
@admataz Apologies for the lack of chat, but I think I agreed to MC this event? I'll get on and confirm the speakers, venue and film crew later.

**Comment by clarkie** [comment]
@admataz Have you done the ~pizza~ beer order for the last couple of events or has Makers been doing it?

- edit: I meant beer, not pizza

**Comment by clarkie** [comment]
@admataz who's our contact at Pusher? Do we go straight to Alex these days?

**Comment by admataz** [comment]
thanks @clarkie  - yes I've been ordering beer - will do again this month - I have it all set up on Ocado already. 

have cc'd you into the emails from Alex

**Comment by claireinez** [comment]
I'll be there next week and will do what I do best, i.e. trawl Twitter.

Let me know if there's anything else I can do on the night. See y'all soon! 🙋

**Comment by clarkie** [comment]
Nice one, thanks @lazlojuly, @claudiamatosa and @claireinez.

**Comment by orliesaurus** [comment]
Email scheduled for Thursday morning - 🚢 🚢 :shipit:

**Comment by clarkie** [comment]
@orliesaurus nice one, thanks!

**Comment by MattJLeach** [comment]
I'll be there as well @clarkie and ready to help out

**Comment by admataz** [comment]
pizza ordered. beer ordered. 🍺 🍕

**Comment by admataz** [comment]
@clarkie please  remember to allow 15 mins for Aris from city js conf to say a few words. we will also be raffling a ticket from them.

**Comment by clarkie** [comment]
@admataz any word from Makers? What about Tiro? 

Also, can you push the slides you used for last month's event?

**Comment by admataz** [comment]
@clarkie  - https://github.com/lnug/slides/pull/5

Haven't heard from Makers or Tiro  - will follow up

**Comment by clarkie** [comment]
@admataz Nice one, thanks

**Comment by clarkie** [comment]
@admataz you've done a cracking job of making the slides as easy as possible! https://github.com/lnug/slides/pull/6

👍 👍 👍 👍 👍 👍 👍 👍 

Who remembers `Deck`? 😱

**Comment by clarkie** [comment]
One question for the group... We've only got two talks this month and one of them is potentially at risk due to the snow ⛄️so I wondered if we should advertise that we'll be opening up some lightening talk spaces?

**Comment by clarkie** [comment]
I've emailed Adam Turnbull at Makers again but we haven't had any confirmation that we're all ok for tomorrow night yet. 😟

**Comment by claireinez** [comment]
> Who remembers Deck? 😱

I do but I wish I didn't.

**Comment by orliesaurus** [comment]
I don't - good job everyone!

**Comment by clarkie** [comment]
Thanks everyone for your help last night! 👍

**Comment by clarkie** [comment]
@elischutze @claireinez do we have a couple of winners for the tickets?

**Comment by claireinez** [comment]
My votes are for https://twitter.com/AliceSuckling/status/968939166879879169 and https://twitter.com/Samatar267/status/968954220459233287

I do wonder why we had so few entries this time, any idea? Does the requirement of the tweet having to be funny stress people out enough not to enter?

**Comment by admataz** [comment]
Thanks @claireinez  - yes those were my favourites too - I'll contact them

Yeah - not sure about the tweet methods - maybe we can discuss other ways of getting people involved for next time.
