### ISSUE TITLE
LNUG #74 - 27th June 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#10]
Hello @lnug/organisers and @lnug/contributors 

We are back at Condé Nast on 27th June. 

Here is the checklist for this month -  choose a task and put your name to it.  or add any you think are needed - some of these will be covered by the arrangements with the venue. 

Please have a read if the docs at https://github.com/lnug/event-planning  - and ask here in the comments if you have any ideas or questions. 

# Checklist (pick a task!)
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github  @admataz
- [x] Who will emcee this month? @admataz
- [x] Registration - this is all on Meetup now  
- [x] Website updates  @admataz
- [x] Monthly Mailer (Mailchimp) @orliesaurus 
- [x] confirm sponsorship arrangements   @admataz
- [x] Slides (usually the MC) @admataz

## Last day checks (Monday before event)
- [x] Confirm with Speakers  @admataz
- [x] Confirm Venue arrangements with Conde Nast  @admataz
- [x] Confirm Video with Pusher 
- [x] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders  @admataz
- [x] Beer orders  @admataz
- [x]  Send attendees list to Michelle @ Conde Nast  @admataz

## On the Night
- [x] MC/host   @admataz
- [x] --- any special announcements or ticket giveaways --- ? 
  - [x] nearForm have a poster they want to display (recruitment)
- [x] Ticket Scan/ Door 
- [x] Doors after 7pm - leave a contact number on a note
- [x] ~T-Shirts~ (we've run out! - need to get more printed!)
- [x] Twitter and tweeting @FabioAntunes
- [x] Keep Gitter discussion rolling
- [x] Speakers & AV 
- [x] Receive Pizza   
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [x] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube
- [x] add those interested in joining lnug orgs
- [x] duplicate this list for next month

Anything else?

**Comment by orliesaurus** [comment]
Mail's going out in the morning (albeit there's a waiting list already...lol)

**Comment by admataz** [comment]
@lnug/organisers @lnug/contributors 
Hey everyone it's LNUG tomorrow! We have great talks lined up...  and another full house 

Who's going to be there to help? Looking forward to seeing you there.

**Comment by FabioAntunes** [comment]
I am! But forgot to rsvp on time so I'm on the waiting list 😅

**Comment by MattJLeach** [comment]
I'll be there @admataz and ready to help out with whatever is needed

**Comment by admataz** [comment]
@FabioAntunes  - I saw that and added you to the "going" list - see you there!

**Comment by admataz** [comment]
I have the videos from Alex and will upload tomorrow
