### ISSUE TITLE
LNUG #75 - July 25th 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#11]
Hello @lnug/contributors  and @lnug/organisers !

I am going to be  out of London for the next two months meetup dates  - so please can someone take ownership here - we have the schedule lined up for July and I've created the meetup page and updated the website. We need an MC and someone to look after things. 

For August we have one potential speaker - and space for another - I'll leave it to you. 

I'm happy to do the ordering of drinks and pizza remotely to keep practicalities of money/sponsorship transactions easier - but the rest is up to you!

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github
- [x] Who will emcee this month? give a big 👏  for @FabioAntunes!
- [x] Registration - this is all on Meetup now
- [x] Website updates 
- [ ] Monthly Mailer (Mailchimp)
- [x] confirm sponsorship arrangements with nearForm
- [ ] Slides (usually the MC)  @FabioAntunes

## Last day checks (Monday before event)
- [x] Confirm with Speakers 
- [x] Confirm Venue arrangements with Condé - @claireinez
- [x] Confirm Video with Pusher / Alex
- [ ] Mailing Reminder [send out a reminder from meetup to anyone who can't make it to cancel and free up places]
- [x] Pizza orders - @admataz
- [x] Beer orders - @admataz

## On the Night
- [ ] MC/host @FabioAntunes 
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door  - handled by Condé security
- [ ] ~Doors after 7pm - leave a contact number on a note~  - not needed
- [ ] ~T-Shirts~ - we've run out
- [ ] Twitter and tweeting - @claireinez
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] Stickers 
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month

Anything else?

**Comment by sielay** [comment]
So far just asking (need to check) - is there anything like pizza/beer that I could ask my current company to sponsor or we are fine? @lnug/organisers ?

**Comment by sielay** [comment]
^ up @admataz

**Comment by claireinez** [comment]
For pizza, I think nearForm has us covered. Conde Nast provide drinks and meals for those with special dietary requirements.

**Comment by sielay** [comment]
If anything pops in mind please shout as I may have a budget. @claireinez

**Comment by admataz** [comment]
Hi @sielay, @claireinez   - thanks for that - sorry for my late reply. Yes we are covered for the moment - will keep it in mind though...

**Comment by admataz** [comment]
@lnug/contributors @lnug/organisers : 

*Big nudge. MC required! We meet next week! *

I will be away until September we need an emcee and someone to take responsibility for running the meetup next week. I can arrange pizza and beer delivery as normal - but the rest is up to you. 

Who's up for it?

**Comment by FabioAntunes** [comment]
I'm up for mcing next meetup and August, if no one is available.

**Comment by admataz** [comment]
@FabioAntunes  - that's great thank you - you're on for next week! (and August if you like... and things come together for that)

As MC - you run the show - so key is making sure you fit everything in to the time available and coordinate with speakers/venue host and videographer on the night. It's all pretty fun and easy. let me know if you have any questions - I'll be around in London till Tuesday afternoon, and back online from the other side of the globe on Wednesday at some point. 

you can find the slides template here [lnug/slides: 🎤The slide deck for the emcee 🎤](https://github.com/lnug/slides) (or make your own  - it's up to you)

**Comment by sielay** [comment]
@claireinez @FabioAntunes can I jump on the mic with "a short code tip"? I saw in the past there was only one proper presentation about RXJS and I have [a funky issue](https://stackoverflow.com/questions/47444581/rx-react-setstate-avoid-cannot-update-during-an-existing-state-transition?noredirect=1#comment89267789_47444581) that most people I interview don't know about. It would take 2-3 minutes tops. 2-3 slides. On 4th I'd remind about my charity cause. Is it won't even be ⚡️ talk.

**Comment by claireinez** [comment]
I'm happy to be point person for chatting to Condé going forward as I chat to Michelle all the time anyway 😂 I'll send over the attendee list to her tomorrow.

Does anyone have access to the lnug email and mailchimp accounts to send out emails? @MattJLeach maybe?

@sielay those talks could be fit into the community announcements portion of the evening but that's up to @FabioAntunes as emcee!

**Comment by trevorah** [comment]
Is there anything I can help with on the night?

**Comment by admataz** [comment]
Thank you @claireinez  - I usually leave the meetup list open till about 2pm on Wednsday as a lot of people change their minds up to that point - and it allows waitlisters to get confirmation. (Although I often just add them to 'attending' at the last minute anyway because it's usually about 10-15 people at that point). Can you send me (DM twitter or email if you prefer) your email address and I'll add you as a manager on the mailchimp account? 


@trevorah  - pick a task! https://github.com/lnug/event-planning/issues/11 or I'm sure you could just be there and help with the ongoing practicalities

**Comment by MattJLeach** [comment]
Hi @claireinez - Sorry I don't have access to the LNUG email or mailchimp. I am happy to take over the email each month though if it helps out.

@admataz - If you want to me take over the monthly emailing, let me know and sort out access, I'll be more than happy to take it off your hands

**Comment by admataz** [comment]
fwiw - I don't think the mailchimp mailer os crucial right now - we are at capacity (+ several on the waitlist) for the meetup - but I do like the idea of keeping it going as a source of LNUG news

Thanks @MattJLeach  - I'll add you to the account too - and if we can all agree between us who is doing it from month to month - @orliesaurus  has kindly been doing it remotely for us from Dallas or somewhere - so keep him in the loop!

**Comment by trevorah** [comment]
@admataz I can do `Food & Drink Area Maintenance` and pick up whatever else the evening throws at us.

**Comment by admataz** [comment]
@claireinez - another thing about the list -  please be sure that the speakers are on the list for Condé - and also the camera person. Alex tells me it will be `Max Thurlow` and he'll be there from about 6:15pm

**Comment by MattJLeach** [comment]
@admataz - I've got the invite and just joined the mailchimp account. I'll have a proper look at it tonight when I get in from work. If it helps I don't mind just taking it over completely if @orliesaurus doesn't want to anymore. It'll save trying to figure out who's doing it each month. Just let me know what you think.

Also, are we still adding anyone on the waitlist onto the list for CondeNast as a couple of friends just asked as they are on the waitlist but keen to come?

**Comment by FabioAntunes** [comment]
Hey @sielay I have no problem with you doing that, my only concern is that is a very specific edge case about RxJS and React not entirely sure how that would be relevant to our attendees who don't have a background on those technologies. 

I guess this would be a really great flash talk for one of our themed events in the future, possibly about RxJS.

If you are really keen in still doing I can squeeze you in.

**Note:**
You will have time to talk about your charity cause no matter what.

**Comment by sielay** [comment]
@FabioAntunes ok, so let's park it for an event we'd do about RX or about async stuff. I can do edge cases of RXJS on bigger architectures. Will just shout about charity, especially since I need to complain a bit (so a* stole my bike yesterday and I will have to walk instead). So 1minute while announcements. Do you need help with anything else?

**Comment by claireinez** [comment]
@MattJLeach Condé want the names of people on the waiting list too (in case any of them turn up) so as long as your friends are on the waiting list, they can get in.

**Comment by MattJLeach** [comment]
That's great @claireinez thanks

**Comment by MattJLeach** [comment]
@admataz - I have just sent a test email to you from mailchimp. Could you check it and if all's OK I'll send it out to the mailing list. I just want to double check as it's my first time doing it.

**Comment by admataz** [comment]
thanks @MattJLeach  - I've forwarded it on to you  - small tweak needed to RSVP url - otherwise looks fine

**Comment by MattJLeach** [comment]
Thanks @admataz I'll let that fixed and sent out shortly. FYI I clicked on the link on the LNUG website to get the URL and it goes to the ti.to link for August 2015. Could we get this fixed as new people might not know to find us on meetup.com

**Comment by admataz** [comment]
>  the ti.to link for August 2015. 

lol blast from the past!
@simonmcmanus  - I think things have been unsettled your latest movements on the website? 

I'm in transit today so won't get to this in a hurry

@MattJLeach  - can you create an issue and label it as a bug here: https://github.com/lnug/website/issues  (and/or have a go at fixing it if you want!)

Thanks!

**Comment by MattJLeach** [comment]
@admataz & @simonmcmanus - Don't worry. Seems to be fine now. Not sure what happened as there have been no commits to the repo but the link is fine again. Weird

**Comment by admataz** [comment]
@MattJLeach  - "Free Ticket" in the page banner is definitely still the wrong link for me

**Comment by jkbits1** [comment]
hi @admataz and everyone - unfortunately I'm too busy to help out this month, hope to be able to do so again soon

**Comment by claireinez** [comment]
RSVPs closed and attendance list sent over to Michelle. See you all tonight!

**Comment by orliesaurus** [comment]
I was going to send the newsletter but then I saw 150 attendees and 20 in the waitlist so there was no reason to send the email out: what do you all think we should do about that? Should we still send an email going forward?
Looking for some feedback on email behaviours ahead of an event!

**Comment by orliesaurus** [comment]
What's left to do on this ticket?

**Comment by admataz** [comment]
@orliesaurus : need speaker videos  - I'm chasing

**Comment by bettiolo** [comment]
Can you link the videos here https://lnug.org/archive.html ?

**Comment by orliesaurus** [comment]
No idea how, i thought it was automagic!? but videos are on our Yt channel
