### ISSUE TITLE
LNUG #76 - August 22nd 2018

### ISSUE THREAD

**Issue by orliesaurus** [lnug/event-planning#12]
Hello @lnug/contributors  and @lnug/organisers !

For August we have one potential speaker - and space for another.

@admataz is still doing the ordering of drinks and pizza remotely to keep practicalities of money/sponsorship transactions easier - but the rest is on us!

Edit by adding your name next to a task or reply to the issue with the task you can help with on the night!

# Checklist
## Pre Event
- [ ] Find/ confirm speakers! and add them as contributors to github
- [x] Who will emcee this month? - @bettiolo 
- [x] Registration - this is all on Meetup now
- [ ] Website updates 
- [x] Monthly Mailer (Mailchimp) - @mattjleach
- [ ] confirm sponsorship arrangements with nearForm
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [ ] Confirm with Speakers - @bettiolo 
- [x] Confirm Venue arrangements with Condé - @bettiolo 
- [ ] Confirm Video with Pusher / Alex
- [ ] Mailing Reminder [send out a reminder from meetup to anyone who can't make it to cancel and free up places]
- [x] Pizza orders - @admataz
- [x] Beer orders - @admataz

## On the Night
- [x] MC/host - @mattjleach
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door  - handled by Condé security
- [ ] ~Doors after 7pm - leave a contact number on a note~  - not needed
- [ ] ~T-Shirts~ - we've run out
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV - @bettiolo 
- [ ] Receive Pizza   - @bettiolo 
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)  - @bettiolo 

## After the event
- [ ] thanks to speakers - @bettiolo 
- [ ] thanks to sponsors - @bettiolo 
- [ ] Stickers 
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month - @bettiolo

**Comment by bettiolo** [comment]
I want to help but I can't edit the document

Happy to do 
- Confirm with Speakers
- Confirm Venue arrangements with Condé
- MC/host
- Speakers & AV
- Receive Pizza
- Food & Drink Area Maintenance (keep the cold beer rolling!)
- thanks to speakers
- thanks to sponsors
- Stickers ???
- duplicate this list for next month

**Comment by orliesaurus** [comment]
Thank you! added you to the list of stuff to do
@bettiolo  here are the slides: https://github.com/lnug/slides - still waiting for the speakers :)

**Comment by MattJLeach** [comment]
@orliesaurus - Have added myself for the mailchimp email and MC/host (although that's also mentioned in the pore event stuff). If @bettiolo is doing it then cool but I'm happy to do it as well just incase.

**Comment by orliesaurus** [comment]
Thanks @MattJLeach

**Comment by claireinez** [comment]
I completely missed this issue but it was announced at the last meetup that there wouldn't be an LNUG this month -- what changed?

**Comment by orliesaurus** [comment]
@claireinez 👍 LNUG never sleeps!

**Comment by sielay** [comment]
@claireinez if it doesn't happen, on meetup it's still up and people are signing up. So? BTW I may help with something.

**Comment by orliesaurus** [comment]
Why would it not happen? Stay positive!

**Comment by admataz** [comment]
I have put in the drinks order for delivery 4-5pm on Wednesday: 

```
Products you've ordered
Cupboard

1 x 10 Coca-Cola Fridge Pack £5.45
2 x 8 Diet Coke £7.00
2 x 6 San Pellegrino Blood Orange £7.58
3 Abbazia Fiorino Prosecco d.o.c. £22.47
2 x 20 Beck's Beer Bottles £26.00
3 BrewDog Dead Pony Club £5.40
3 BrewDog Punk India Pale Ale IPA £5.40
2 x 8 Goose Island Variety Pack £23.00
3 Laverstoke Organic Lager £5.37
3 Meantime London Lager £5.40
3 Meantime London Pale Ale £5.40
3 Sam Adams Boston Lager £5.00
2 x 20 Stella Artois Lager £24.00
3 St. Mungo Lager £5.25
1 White 2ply Paper Napkins, 33cm £2.39
2 x 4 Pilsner Urquell £8.00
1 x 20 Peroni Nastro Azzurro Chilled To Your Door £20.00
```

Also paid the Pizza bill from last month and will put a new order in on Monday

**Comment by claireinez** [comment]
@admataz it might be worth reducing the pizza order a bit -- we had less than 70 attendees last week and Condé Nast would prefer we keep our numbers to less than 100. All the pizza does get eaten, I don't think we'd ever have a problem with that though 😂

**Comment by admataz** [comment]
Thanks @claireinez  - I have reduced the pizza order slightly to 40 instead of 50 - please can you keep a headcount  - I'd be interested to keep track of how many people are attending each meetup and try to identify when we have dropoff.  In the past when 4th Wednesday is not the last Wednesday (as it is this month) it's been a better than normal  turnout - and David is a seasoned speaker talking about a product that has a bit of hype around it - so we may get a high turnout this month - but who can tell?! 40 should be enough...

also - thank-you in advance for looking after the attendance list and getting that to Michelle.

**Comment by MattJLeach** [comment]
@admataz @claireinez - I've been a bit busy lately but will be sending out the email when I get in from work tonight so hopefully be a reminder for people that it's on this week.

**Comment by claireinez** [comment]
@mattjleach could you remind people they need to have their full names on the RSVP? The meetup page was originally set up not to ask for their full name and also allowed guests. I've messaged people individually about it but would be good to remind people their full name is needed or building security won't let them in. Thanks! :)

**Comment by MattJLeach** [comment]
@claireinez just logged onto Mailchimp and there's a note by @orliesaurus saying not to send (waiting for community announcements) so I'll leave it for him to sort out this month. Let me know if anything else is needed from me

**Comment by orliesaurus** [comment]
@claireinez weird I cloned the prev meetup's and edited only the parts that needed to be edited. Any idea if those are settings that "reset" every time? Good to know though!

We can use the meetup tool to contact all those without a full name who didn't specify a full name and remove them if they fail? Since it's enforced....

**Comment by orliesaurus** [comment]
@MattJLeach yeah I was waiting for some stuff from cloudflare but they're not ready for the announcement yet - so we can send it ( oh and we have one extra speaker ) Feel free to send and so some spellcheck if u want - thx

**Comment by orliesaurus** [comment]
Awesome, good job y'all! 🎓

**Comment by orliesaurus** [comment]
VIdeos Uploaded and I think we're done here

**Comment by bettiolo** [comment]
@orliesaurus can you link the videos here: https://lnug.org/archive.html ?

**Comment by orliesaurus** [comment]
We'll see about that :D
