### ISSUE TITLE
LNUG #77 - 26th September 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#13]
Hi all @lnug/organisers  

We have a GraphQL extravaganza lined up for the 26th... Who is around to help?
 
Please pick a task or two or three for our next meetup and add your name to it...

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github @admataz
- [x] Who will emcee this month? @admataz
- [x] Registration - this is all on Meetup now @admataz
- [x] Website updates  @admataz
- [ ] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)   @admataz

## Last day checks (Monday before event)
- [x] Confirm with Speakers @admataz
- [x] Confirm Venue arrangements with Condé Nast  @admataz
- [x] Confirm Video with Pusher  @admataz
- [x] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders  @admataz
- [x] Beer orders - @admataz

## On the Night
- [ ] MC/host   @admataz
- [ ] Special Announcements and slides
  - [ ] ticket offer and promo for halfstack london
  - [ ] nodeconf EU
  - [ ] let's set up a jobs board on gitter
- [x] Ticket Scan/ Door (venue does this)
- [ ] Doors after 7pm - leave a contact for latecomers/ those not on list
- [ ] ~T-Shirts~
- [ ] Twitter - @clarkie
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) @Silverwolf90

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] Stickers 
- [ ] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month

Anything else?

**Comment by clarkie** [comment]
I'll be there this month 👍 

I can do doors, tweeting, whatever

**Comment by trevorah** [comment]
Samesies!

**Comment by bettiolo** [comment]
Do you need anything from me this month? I am happy to come and do MC again or just help with admin stuff.

**Comment by admataz** [comment]
Hey @bettiolo  thanks! - all organised so far -  I'll MC this month - we'll need help on the night with general running - tweeting, meeting greeting, pizza boxes and drinks area etc etc.

**Comment by bettiolo** [comment]
OK, I will come over and help, I will update the slides if no-one did so far /cc @orliesaurus

**Comment by MattJLeach** [comment]
Unfortunately I'm not going to make tonight so have updated my RSVP on meetup. Have a great evening and I'll be back next month

**Comment by bettiolo** [comment]
Slides updated: https://github.com/lnug/slides/commit/72f7fc67b70ad510d3569477b08e86483d3a2682

On my way to the venue.
