### ISSUE TITLE
LNUG #78 - 24th October 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#14]
Hi all @lnug/organisers  

We meet next week!!  who's coming?
Pick a task or two or three and add your name to it...

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github @admataz
- [x] Who will emcee this month?
- [x] Registration - this is all on Meetup now 
- [x] Website updates  @admataz
- [x] Monthly Mailer (Mailchimp)
- [x] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers @admataz
- [x] Confirm Venue arrangements with Condé Nast  @admataz
- [x] Confirm Video with Pusher / Alex @admataz
- [ ] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders  @admataz
- [x] Beer orders - @admataz

## On the Night
- [x] MC/host   @admataz
- [x] Special Announcements and slides
  - [x] nodeconf EU
  - [x] jobs board on gitter
- [x] Ticket Scan/ Door (venue does this)
- [ ] Doors after 7pm - leave a contact for latecomers/ those not on list
- [ ] ~T-Shirts~
- [x] Twitter 
- [ ] Keep Gitter discussion rolling
- [x] Speakers & AV 
- [x] Receive Pizza   
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [x] thanks to speakers
- [ ] thanks to sponsors
- [ ] Stickers 
- [x] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [x] duplicate this list for next month

Anything else?

**Comment by admataz** [comment]
bump @lnug/organisers. anyone?

**Comment by trevorah** [comment]
I can be the food and drinks wizard

**Comment by MattJLeach** [comment]
Sorry @admataz have been really busy lately. I will be there tomorrow though and happy to help with anything needed.

**Comment by admataz** [comment]
thanks @MattJLeach and @trevorah   - see you tomorrow!

**Comment by admataz** [comment]
videos from the event now online: https://www.youtube.com/playlist?list=PLam_80-FY3vQE2I_NP0F3dTFsVHGrTTVX
