### ISSUE TITLE
LNUG #79 - 28th November 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#15]
Hi all @lnug/organisers  

Pick a task or two or three and add your name to it...

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github @admataz
- [ ] Who will emcee this month?
- [x] Registration - this is all on Meetup now 
- [x] Website updates  @admataz
- [ ] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers
- [x] Confirm Venue arrangements with Condé Nast 
- [x] Confirm Video with Pusher / Alex
- [ ] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders
- [x] Beer orders 

## On the Night
- [ ] MC/host   
- [ ] Special Announcements and slides?
- [ ] Ticket Scan/ Door (venue does this)
- [ ] Doors after 7pm - leave a contact for latecomers/ those not on list
- [ ] ~T-Shirts~
- [ ] Twitter 
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] Stickers 
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month

Anything else?

**Comment by admataz** [comment]
@lnug/organisers, @lnug/contributors   - who's available to help run LNUG next week? 

I have a potential clash of plans - it would be great if someone could step up and take ownership of next week's meetup

**Comment by MattJLeach** [comment]
@admataz - Sorry but I have plans that have come up and won't be able to make next week

**Comment by FabioAntunes** [comment]
I will be there, and I can help with everything.

**Comment by orliesaurus** [comment]
yikes I forgot about the email! Good luck everyone!
