### ISSUE TITLE
Better ways to help

### ISSUE THREAD

**Issue by leggsimon** [lnug/event-planning#16]
@admataz and I were chatting at last nights LNUG about how we could better help out Adam organising an event. I think here would be a good way for us to discuss how we can help out a bit better maybe. 

I’m of the opinion that for me, having a list of tasks and letting people "pick them up" doesn’t necessarily work (certainly not for me) and that people being assigned a task each month ensures everything gets done and it doesn't always fall to Adam to do a lot of things. 

What do people think? 

NB: I maybe haven’t explained myself well enough so please ask if you want clarification.

**Comment by admataz** [comment]
Thanks @leggsimon - and thanks for putting up with my kvetching on wednesday night. 

everyone stay tuned for details up for an organisers-only meetup - it will be good to see you all and we can catchup on all things
