### ISSUE TITLE
Getting organised... let's meet!

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#18]
@lnug/contributors @lnug/organisers 👋 

Can we organisers meet next week Wednesday 20th to talk about upcoming LNUG plans? Add a comment here to let me know if you can make it. Time and location TBC... somewhere central and probably early evening.

Things I'd like to cover: 
- [x] LNUG's involvement in  upcoming events and meetups in 2019 (I know, it's late March already)
- [x] organisers - who's still around to help, and with what - who's new?
- [x] hosting and venue offers
- [x] sponsorship offers/ efforts
- [x] other... ? add anything you want to cover... 

Mostly -  it will be good to see you all

**Comment by MattJLeach** [comment]
Hi @admataz 

I can do Tuesday, Wednesday or Friday next week (after 6.30pm). Let me know if there'll be a couple of beers involved and I'll leave the bike at home.

**Comment by neshka** [comment]
Hi @admataz,
Monday, Tuesday, Wednesday or Friday after 6pm are ok for me.

**Comment by Ankcorn** [comment]
Hi, I'd like to get involved but can't do Wednesday's. Tuesday works best for me.

**Comment by ketsthechanger** [comment]
Hi Adam, I'd like to get involved in LNUG. Can do after 6pm.. please let me know.

Cheers, Ketan

**Comment by admataz** [comment]
Ok  - maybe Tuesday (i.e. tomorrow)... somewhere central after 6pm   will confirm later today 

We'll need a venue - if anyone has a good idea... somewhere central please suggest here

@claireinez @clarkie @elischutze @FabioAntunes @simonmcmanus @trevorah @graycodes @bettiolo 
are any of you around?

**Comment by leggsimon** [comment]
I’m in Germany so can’t unfortunately

**Comment by hewIngram** [comment]
I'd be well up for getting involved in helping out and organising if you're looking for new volunteers @admataz?

Tuesday works for me

**Comment by admataz** [comment]
Good morning! 🌦 

@MattJLeach, @neshka, @Ankcorn, @ketsthechanger, @hewIngram  
...and anyone else from @lnug/contributors  or @lnug/organisers 

So we are planning to meet this evening at 6pm - has anyone got office space with a meeting room they could donate for an hour? Otherwise we can go straight to a pub. 

Let us know in the comments....

**Comment by simonmcmanus** [comment]
@admataz how many people are we talking? I can ask about 1st floor of TOG.

**Comment by hewIngram** [comment]
Not at all Central or that convenient, but we've got some space upstairs at Google Campus if that works for anyone?

**Comment by admataz** [comment]
@hewIngram what's the address? 

@simonmcmanus so far 6 - or 7 + a dog if you are hosting 😄

**Comment by simonmcmanus** [comment]
ok, will ask now, google campus works for me too, assuming its dog friendly :)

**Comment by hewIngram** [comment]
4-5 Bonhill St, Shoreditch, London EC2A 4BX

Kind of between Old St and Liverpool St but close to neither 😅

**Comment by simonmcmanus** [comment]
we are ok to use the engineering room on 3rd floor:

https://www.theofficegroup.co.uk/office/2-stephen-street/

Im gonna head into town now, see you all later.

**Comment by hewIngram** [comment]
Sweet, see you later @simonmcmanus

**Comment by admataz** [comment]
great! so to confirm - we meet at TOG that's super convenient and central. 

Thanks all  - see you later... I'll meet you in the lobby at 2 Stephen St around 6pm

**Comment by admataz** [comment]
does everyone here have access to the gitter room? https://gitter.im/lnug

**Comment by ketsthechanger** [comment]
See you all

**Comment by Ankcorn** [comment]
See you all there 🐕

**Comment by ketsthechanger** [comment]
Hey adam, can you please send your number ? Haven't met anyone of you before

**Comment by admataz** [comment]
my number is 07757234443 if you are here and need someone to let you in. we are upstairs.

**Comment by ketsthechanger** [comment]
Sorry, Had to stay in the office.. still in office, will catch up with you adam tomorrow on call.. hope that's fine

**Comment by MattJLeach** [comment]
Good catchup tonight. Here's the link to the podcast I mentioned. https://softskills.audio/

**Comment by Ankcorn** [comment]
Thanks @admataz for the :beer: and organising this.

**Comment by admataz** [comment]
Hey all - thanks for coming to the meeting earlier. Great to catch up. I'll put together some notes and actions we discussed and share

**Comment by admataz** [comment]
Here's a summary of what we discussed last night. 

Sorry you couldn't make it @ketsthechanger  - come say hi at next Wednesday's meetup and let's discuss how you can get involved. 

## Notes: 

### 1. Intros and our envisaged roles/ ideas about LNUG. 
- My takeaway from this is that we are all keen to maintain LNUG as an inviting and enjoyable space for attendees - that we are doing something right - and want to keep doing it (whatever it is)
- We would like LNUG to continue to offer good talks
- We would like to be support to our community in 2 main ways - finding their way as professional developers (entry level)  - contributing knowledge back to the community (help first time speakers etc)
- LNUG can be more than a monthly event - and it would be good to maintain some momentum in the communications via gitter and twitter and other channels through the month. 

### 2. An LNUG 'manifesto' or common reference for defining our purpose 
I read a doc to you all which I have been using to communicate about LNUG when potential sponsors and partners ask. Use it if it feels like the right thing. I've added it [here](https://github.com/lnug/event-planning/blob/master/about-lnug.md)

### 3. Podcast idea
new territory for us all - @simonmcmanus and @MattJLeach  and @admataz  all keen to help

Let's see where it takes us. Repos created here to collect ideas and get started: 
https://github.com/lnug/lnug-podcast

### 3. Upcoming Meetups
Confirming our approach - everything is communicated through github - read the guides and readme in this repos for more info

#### Mixing up the MC duties
We want to represent more of our community in the organisations - so it should not be only @admataz that does the MC duties. @MattJLeach and @seanmtracey have kindly volunteered for the next couple meetups - would like to see more in terms of diversity too - so we should keep rotating and encouraging other members -  and this frees me up to make LNUG announcements where required. 

#### handling recruitment at meetups
In the past we allowed people hiring and people looking for jobs to take the mic for a couple minutes self-promo. New job seekers were often to scared to present themselves and the long stream of recruiters got boring for everyone. 

Our new proposal is to have a "Jobs Table" at meetups - that should be the meeting place for recruiters and job seekers. This can be monitored/facilitated by an LNUG organiser - and promoted by the MC - let's see how this goes. 

### getting speakers
- We should be contacting speakers at conference events and inviting them
- We need to encourage diversity
- Let's all speak to our workmates and encourage some stories
- All monitor and feedback or at least provide a seconder for talk proposals
- say "thanks for your proposal" in less than 48hrs - any of us can do this

### 4.  City JS conf
We have a slot for a node.js workshop on May 1st -  @Ankcorn and @hewIngram volunteered - there's another issue for this (#19)

### 5. Hosting
In principle we should be open to new venues - moving around can be good for our members. We should follow up the businesses that have com forward and visit them to see. It would be good to rotate. 

### 6. sponsorship
We still want to avoid admin burden - but would like to involve potential sponsors when they come forward. We have some ideas for where contributions can be made directly: 

- tshirts
- organisers tshirts
- rollerbanner
- stickers
- costs towards a mentoring workshop
- costs to bring external speakers


### 7. Organise repos
I've renamed and cleaned up the private 'planning' repos and added you all as organisers so you should have access to https://github.com/lnug/organisation. Let's use that for discussions on sponsorship, etc. 

Thanks again - please add any feedback and notes or anything I missed

**Comment by leggsimon** [comment]
>Our new proposal is to have a "Jobs Table" at meetups - that should be the meeting place for recruiters and job seekers. This can be monitored/facilitated by an LNUG organiser - and promoted by the MC - let's see how this goes.

I really like this, I did occasionally question whether the “in the break, go find the people with their hands up” thing worked at all.

> In principle we should be open to new venues

The FT may be more keen to do this once we’ve moved to our shiny new office in a couple of months.

**Comment by admataz** [comment]
ok - I'm closing this  - thanks all for your input and coming along - I think the few follow on points have their own momentum and specific issues and repos.  Feel free to open more issues for discussion as and when you need to. 

And let's meet again in a few months.

**Comment by claireinez** [comment]
Ah sorry to have missed this -- I was on holiday for a few weeks and didn't look at github at all. Thanks for the summary @admataz and I'll see you all on Wednesday.

**Comment by admataz** [comment]
Hi @claireinez! hope you had a great holiday - see you on Wednesday

**Comment by trevorah** [comment]
Sorry I missed this as well, I've been having a nightmare trying to sort out a flat move. I'm moving this weekend so I can't make it to this months meetup, but I'm looking forward to next months!
