### ISSUE TITLE
Mentors/ Workshoppers required for London CityJS Conference

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#19]
@lnug/contributors @lnug/organisers 

The organisers at London CityJS conference have a session for a node workshop around the conference time on Wednesday 1st May. 

Who would be up for running a workshopper (nodeschool.io or other programme) for attendees? Probably intro to intermediate level

Please respond in the comments here, or email me: contact@lnug.org.

**Comment by leggsimon** [comment]
Would love to but unfortunately I'm away

**Comment by Ankcorn** [comment]
Hi @admataz it would be good to find out more about this.

**Comment by admataz** [comment]
Thanks @Ankcorn  - I think you were chatting with @hewingram too? I will put you in touch with the organisers  - can you send me your email addresses to adam@admataz.com? thanks

**Comment by hewIngram** [comment]
Lets do this @Ankcorn 

![](https://media.giphy.com/media/r2BtghAUTmpP2/giphy.gif)

**Comment by nikcorg** [comment]
What kind of hours are we talking about? I can probably be available, but would need to know more about the parameters.

If email is the preferred channel for communicating, I can be reached at niklas.lindgren@iki.fi.

// cc @admataz

**Comment by admataz** [comment]
wow, things have moved quickly! Nice work. 

https://twitter.com/cityjsconf/status/1109051266821427201
![](https://pbs.twimg.com/media/D2Qj-WdWkAEHurF.jpg)

thanks @nikcorg! - if you're at the next meetup (Wednesday 27th) please come along and introduce yourself to @Ankcorn  and @hewIngram and see if there's anywhere you can help with what they're doing.. 

I'm going to close this issue now because things have moved on.
