### ISSUE TITLE
Nodeschool 2018

### ISSUE THREAD

**Issue by clarkie** [lnug/event-planning#2]
I'm hoping to organise a nodeschool.io event in an evening in the first week of April. I've already roped in a few volunteers to help out but if anyone else is interested in getting involved then jump on board and get involved. 

A list of bits and pieces that we'll need to get sorted

- [ ] Date / time tbc
- [ ] Venue tbc
- [ ] Mentors
- [ ] Advertising the event - we can use the LNUG meetup to create an event and track attendees

So far I have "mentor-in-principle" from 
- @clarkie
- @claudiamatosa 
- @philipisapain 
- @lazlojuly 
- @adrianblynch 
- @graycodes
- @jkbits1

**Comment by admataz** [comment]
Hey @clarkie  - sounds great!  I'll be out of town for the first 2 weeks of April - so won't be available to help on the day - but happy to help in the run-up where I can.

**Comment by nikcorg** [comment]
My calendar is still quite empty in April, so I'd be very happy to chip in as a mentor and bang on about the event on SoMe.

**Comment by admataz** [comment]
guess we all got too busy in April? - let's definitely organise something for May or June. From the chat I had with Makers - they would be keen to host
