### ISSUE TITLE
Pusher promotional details for slides newsletter and meetup pages

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#21]
Pusher have asked for some detail to be shared in exchange for their contribition:

Please make use of these when preparing slides and newsletters, and any event announcement where Pusher are involved as sposnsors. 

Thanks!

cc @orliesaurus @seanmtracey 

----

About Pusher Blurb – please include this at the bottom of your Meet-Up.com event page in the same way you’d mention your event hosts etc.
We Transfer Link – This contains a small groups of assets. Please download these and keep a copy.
1. Pusher Logo – This generic logo can be featured in your own slides where appropriate
2. - 3 Pusher Splash Slide, Pusher Products, Pusher End Slide – Please incorporate this into your pre-talk slide deck amongst your own slides for rotation. If you have a generic slide deck you play during the networking / beer / pizza sections of your event please leave this on rotation.
Pusher Slide Show Video – This is also available to be featured into your slide deck. A simple 12mb video. If it’s feasible for you to incorporate this into your pre-talk slide decks then please use this also.
The assets can be downloaded here: https://we.tl/t-TThp4r9LrT
 
About Pusher Blurb:
Video Recording Sponsored by Pusher:
You can view previous event talks and more by visiting the Pusher App YouTube channel!
 
Pusher is a hosted service with APIs, developer tools and open source libraries that greatly simplify integrating real-time functionality into web and mobile applications.
 
Pusher will automatically scale when required, removing all the pain of setting up and maintaining a secure, real-time infrastructure.
 
Pusher is already trusted to do so by thousands of developers and companies like GitHub, MailChimp, the Financial Times, Buffer and many more.
 
Getting started takes just a few seconds: simply go to pusher.com and create a free account. Happy hacking! 

----

![1  Pusher Logo](https://user-images.githubusercontent.com/395101/54885951-3beee780-4e7a-11e9-9db2-02f178ad8224.png)
![2  Pusher Splash Slide](https://user-images.githubusercontent.com/395101/54885952-3c877e00-4e7a-11e9-920c-465346c0bf80.jpg)
![3  Pusher Products](https://user-images.githubusercontent.com/395101/54885954-3c877e00-4e7a-11e9-98bd-1fa34f5ca875.jpg)
![4  Pusher End Slide](https://user-images.githubusercontent.com/395101/54885955-3c877e00-4e7a-11e9-9fd7-a0e6986568cc.jpg)

**Comment by orliesaurus** [comment]
Thanks!

**Comment by admataz** [comment]
These are now a part of the MC slide deck
