### ISSUE TITLE
LNUG #83 - April 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#22]
@lnug/contributors @lnug/organisers

Who's going to be around to help in April? :)

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? @MattJLeach 
- [x] Registration - this is all on Meetup now
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @neshka 
- [x] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues @neshka 
- [x] Confirm Venue arrangements @admataz 
- [x] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [x] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door @Ankcorn 
- [ ] Doors after 7pm - leave a contact number on a note
- [x] Jobs/recruitment table @Ankcorn 
- [x] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [x] Receive Pizza   
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) (@trevorah)

## After the event
- [ ] thanks to speakers @neshka 
- [x] thanks to sponsors
- [x] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [x] duplicate this list for next month @neshka 

Anything else?

**Comment by admataz** [comment]
hi @neshka  - thank you for kicking off the todo list for next month!

I'm about to head off to the airport - I'll add my name to relevant tasks now - but meanwhile - can someone create the event on meetup? I've updated the website from the talk descriptions - it should be a case of making a copy of the last meetup - and changing the details. Make sure you get the dates right!!

**Comment by neshka** [comment]
Hey! I can create the next event.

**Comment by orliesaurus** [comment]
@admataz any community announcements this month?

**Comment by admataz** [comment]
Hey @orliesaurus  - yes - please mention: 

- City JS Conference 20% community discount (image: https://user-images.githubusercontent.com/395101/54816645-b823d800-4c8c-11e9-9d38-54c1c495f1f5.png)

- LNUG-run node.js workshop at CityJS conf on May 1st  (image: https://camo.githubusercontent.com/7de3ff7bc598f10a9a178cea29c42ada1ec234ae/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4432516a2d5764576b4145487572462e6a7067)

- Community discount for a node conference in Amsterdam: 
```
We are organising a Node Conference on the 7th of June in Amstedam - www.nodeconference.nl with several Node Collaborators joining.   Perhaps it could be of interest for your group?   I would happily discuss any form of collaboration and value your opinion on interesting topics, meanwhile I went ahead and already created a temporary discount for the community with the code WeLoveNode or via the direct link: https://www.eventbrite.co.uk/e/nodeconf-nl-tickets-55400855450?discount=WeLoveNode
```

- Amsterdam.js conf (different event to above)  - we raffled a ticket at the last meetup and they also have a doscount code for LNUG: `15% discount code for your members, in case you'd like an extra perk for your community: https://www.eventbrite.com/e/amsterdam-jsnation-conference-2019-tickets-53358526790?discount=LNUGdiscount`

- new LNUG organisers helping out - big thanks to them (@neshka, @hewIngram, @Ankcorn, @seanmtracey)

-

**Comment by orliesaurus** [comment]
Ok all done

**Comment by Ankcorn** [comment]
Hey, happy to help out on the night.

Maybe like twitter and recruitment table?

**Comment by seanmtracey** [comment]
Ditto! Will also be able to help on the day :)

**Comment by Ankcorn** [comment]
I can get there early if that helps :)

**Comment by orliesaurus** [comment]
@Ankcorn @seanmtracey  put your handles next to the checklist (and tick it if its an activity you can complete pre-meetup)

**Comment by Ankcorn** [comment]
Can't edit it. 

Can do the door and jobs table! 👍

**Comment by hewIngram** [comment]
I think we had someone lined up to emcee right? Was it @MattJLeach ?
(this 10000% *isn't* me saying I'll do it if it wasn't him/he can't do it anymore)

**Comment by MattJLeach** [comment]
Yes I'm good to do the emcee this time round. It won't let me edit the top post to add myself. Could someone have a look at my privileges please? (@admataz)

**Comment by claireinez** [comment]
I'll be around to help out too (I also can't edit the original post)

**Comment by admataz** [comment]
Hi all, 
Apologies for the silence my side - I've been away with family and off the grid... 

I've changed some team permissions for this repos - @MattJLeach  - can you try edit this issue again?

**Comment by MattJLeach** [comment]
Thanks @admataz 
I have added myself as the emcee for this one

**Comment by admataz** [comment]
@MattJLeach  - all good from your side? I may have some additions to the slides for you as a last push promo for CityJS conf

Otherwise - I've confirmed all arrangements with hosts and speakers and catering and video - and beer and beverage delivery set to arrive 5-6pm at Conde Nast. 

Looking good!!

**Comment by MattJLeach** [comment]
Hi @admataz - I'm all good for tomorrow. As it's my first time doing the emcee is there anything I should prepare / be aware of?

**Comment by admataz** [comment]
@MattJLeach  
- the slides  - checkout from https://github.com/lnug/slides and update all the specific details  - let me know if you have any problems
- make a list of announcements  - make sure you catch everything (not a lot this month - the most important are the city js conf and the jobs table) 
- and have a think about evening's timings and running order - and run it through in your mind
- get there for 6:15 or so and have a chat with speakers and camera guy (Max) before things kick off
- enjoy!

I'll be there - so if you have any questions - just ask!

**Comment by MattJLeach** [comment]
Thanks @admataz

**Comment by MattJLeach** [comment]
Hi @admataz 

Do we have confirmed talks for next month to add to the slides? I see we have "Native implementation of curl in Node" but I'm not sure what the speakers name is?

Also, I tried pushing the slide changes to a branch on the repo as I also fixed a couple of small bugs but I don't seem to have the ability to do this.

Thanks
Matt

**Comment by admataz** [comment]
@MattJLeach  - sorry - I messed up the github org default permissions at some point - you should be able to write to [lnug/slides](https://github.com/lnug/slides) now. 

We don't have a second confirmed speaker yet - but it's a good opportunity to encourage people to step up with a talk... 

There certainly is an air of mystery around the speaker! that's ok - but if you're listening @chinrank - feel free to fill us in with your name/etc if you want!

**Comment by MattJLeach** [comment]
@admataz - Have created a pr on slides repo so you can double check that you're happy with it

**Comment by admataz** [comment]
good work last month everyone - thanks!
