### ISSUE TITLE
Alternating LNUG meetup venues... 

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#23]
In our last organisers meeting we discussed the idea of moving venues occasionally - to keep it fresh - and via changing location - keep many parts of our community active. we agreed a rotation would be good - and I mentioned the idea to our current long-term hosts at Condé Nast and they thing it sounds great too. 

### Potential venues 

- [ ] CloudFlare

First off - today I had a message from CloudFlare - and *this Thursday (25th April)* they are hosting an opening party at their new venue behind County Hall  - capacity 280. I've said I will go - anyone else keen to join me? let me know in the comments and I'll forward on your details for the list.

- [ ] Zoopla

Also had a follow up from Zoopla - who were in contact before - but I haven't managed to get there. I'm going to arrange a visit - let me know in the comments if you want to come along. 

---

Please add any other venue considerations here - and let's use this issue to discuss thoughts and feedback for now. 

---

**Comment by Ankcorn** [comment]
CloudFlare were great hosts for code bar a few weeks ago! The office was a little hard to find so we would need to make sure we had somebody loitering outside to catch fans of javascript and point them in the right direction.

👍

**Comment by admataz** [comment]
superceded by #34
