### ISSUE TITLE
LNUG #84 - May 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#24]
@lnug/contributors @lnug/organisers

Who's going to be around to help in May? :)

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? @leggsimon 
- [x] Registration - this is all on Meetup now
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @neshka 
- [ ] Monthly Mailer (Mailchimp)
- [x] Slides (usually the MC) @leggsimon 

## Last day checks (Monday before event)
- [ ] Confirm with Speakers via the github issues
- [ ] Confirm Venue arrangements @admataz 
- [ ] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door 
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table 
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza   
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) (@trevorah)

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by seanmtracey** [comment]
Sorry all, I won't be able to help with this event. Will be at Bristol that entire week. Hope all goes smoothly :)

**Comment by hewIngram** [comment]
Do we have someone lined up to MC it?

**Comment by admataz** [comment]
hi @seanmtracey  - thanks for letting us know - have a great time in Bristol

@hewIngram  - nothing confirmed so far - but I'll be happy to do it if no one volunteers (leaving that space open!)

**Comment by adamdiy** [comment]
Hello, I'm a long-time attendee and /organiser lurker, ready to help out with anything and everything this month 

My new place is also open to potential sponsopship / ticket giveaways at LNUG: who's best to speak to? @admataz ?

**Comment by leggsimon** [comment]
I could probably MC if you want? It’s on the 22nd? Is that right, it’s normally last Wednesday of the month, no?

**Comment by admataz** [comment]
@adamdiy  - sounds great!  - will you be there next Wednesday and we can talk about how you can contribute? If you have anything specific that you want to giveaway for May's meetup, please add it here in a comment and we'll incorporate it into the evening's plans - or if you prefer email me: adam@admataz.com

@leggsimon that would be billiant! yes it's the 22nd (next week Wednesday)

**Comment by adamdiy** [comment]
@admataz  nothing for May unfortunately, but will see you at LNUG next week and figure out what works best for June!

**Comment by trevorah** [comment]
I've got a company meeting that finishes at 7, so I won't be around to help set up LNUG this month. I should be around during and after to help clear up though!

**Comment by leggsimon** [comment]
@admataz are you able to share anything that needs saying with me please

**Comment by admataz** [comment]
Hi @leggsimon  -  just waiting for confirmation on a potential ticket giveaway - other than that we are pretty light on the announcements this month - so just the usual - sponsors, etc. Let me know if you want to go through any of it.

**Comment by arakno** [comment]
Hi , I could be at the door, receive pizza, etc...


<webdeveloper>
    Name:  Paulo Basto
    Email:  pbasto@arakno.net
    Web:    www.arakno.net
    Twitter: @arakno
    Skype:  arakno.net
    Mobile: [+44] (0)7404597489
</webdeveloper>

**Comment by leggsimon** [comment]
@admataz yep, could we have a call tomorrow. Need to get the slides from you as well

**Comment by MattJLeach** [comment]
Hi @admataz, sorry but I'm not going to make it tonight. Have a great time everyone and I'll see you all next month

**Comment by admataz** [comment]
@leggsimon  for slides you can get the latest from https://github.com/lnug/slides and update  - let me know if you have any issues

also have a quick read:   https://github.com/lnug/event-planning/blob/master/MC-guide.md  - mostly common sense - but worth checking over

I'm mostly in meetings from 1pm - have you got time for a quick chat before then? My number is 077757234443 - speak later!

**Comment by admataz** [comment]
@arakno  - great! thanks for your help - see you later!

**Comment by admataz** [comment]
videos: https://www.youtube.com/watch?v=cBH2L2LDRek&list=PLam_80-FY3vSWxFY2d4iJ0OUwUCTxYrZV
