### ISSUE TITLE
LNUG #85 - June 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#25]
@lnug/contributors @lnug/organisers

Who's going to be around to help in June? :)

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? - @seanmtracey 
- [x] Registration - this is all on Meetup now
- [x] Website updates
- [x] Create Meetup event (copy last month) @neshka 
- [x] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC) - @seanmtracey 

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues @neshka 
- [x] Confirm Venue arrangements @admataz 
- [ ] Confirm Video with Pusher @admataz
- [ ] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host @seanmtracey 
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door @seanmtracey @Ankcorn 
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table @seanmtracey 
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza   @Ankcorn 
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!) @trevorah

## After the event
- [x] thanks to speakers @neshka 
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by seanmtracey** [comment]
I'm happy to MC / jobs table / ticket scan. Whichever is if anybody else has a preference :)

**Comment by orliesaurus** [comment]
Sending newsletter out now

**Comment by ketsthechanger** [comment]
Sorry, was on holiday for the past month! Happy to take over activity for July meetup @admataz

**Comment by Ankcorn** [comment]
Well Volunteered Mr Tracey! I will be there and happy to help with anything. If somebody tells me what Ticket Scan/ Door is I can take that off your hands @seanmtracey and let you have time to get ready to MC

**Comment by hewIngram** [comment]
I like the idea that @seanmtracey has an intense and focussed pre-mcing routine that he goes through. From what I've seen it mostly involves drinking beer.

I'll be around and happy to do anything.

**Comment by seanmtracey** [comment]
Sorted! I'll MC :)

For the curious, @hewingram is correct. Just imagine the Rocky montage scene, but with beer 🍻

**Comment by admataz** [comment]
Hi all - thanks for stepping up and taking on tasks.

**Comment by adamdiy** [comment]
Hi all, I mentioned to @admataz last month that we have 3 free tickets to raffle off for ServerlessDays! Have attached a super-basic background slide here, winners can email me to register/get their ticket

Don't know if you want to do it as MC @seanmtracey ? Otherwise I am happy to. Imagine we should wait towards the end?

[LNUG slide 26Jun2019.pdf](https://github.com/lnug/event-planning/files/3321399/LNUG.slide.26Jun2019.pdf)

**Comment by seanmtracey** [comment]
@adamdiy More than happy to do it during the community announcements, but if you want to talk for a few moments about Serverless Conf and announce the raffle during the community announcements, we can run the raffle at the end. What do you think?

**Comment by adamdiy** [comment]
Yep, I'm happy to speak for a minute about the conference and the raffle
during community announcements, then leave it to you to draw at the end :+1:

**Comment by seanmtracey** [comment]
Cracking :D

**Comment by MattJLeach** [comment]
Hi @admataz 
Unfortunately, I'm not going to make it again this month. Things have been really busy the last couple of months. I hope to be back next month. Have a great meetup everyone

**Comment by admataz** [comment]
hey @MattJLeach  - thanks for letting us know... also been mad my side  - hopefully see you next month - have you and @simonmcmanus had any joy with the podcast idea (my guess is no - it's beeen hectic!)  - do you want us to give a shout for help at the meetup?

**Comment by admataz** [comment]
videos: https://www.youtube.com/watch?v=Cg_psyqJo8I&list=PLam_80-FY3vS64uOTJDVAqSWffyVHB8E9
