### ISSUE TITLE
Organisers meetup

### ISSUE THREAD

**Issue by hewIngram** [lnug/event-planning#27]
Hello lovely LNUG organisers.

How do people feel about an organisers meetup next week or the following to chat about all things LNUG?

It'd be great to catch up on:

- General event stuff (how can we be more useful @admataz)
- Podcast update
- Diversity (I'm acutely aware that our speakers, MCs and even us organisers are predominantly white men in fairly senior dev roles - how can we encourage more diverse speakers/organisers).

What else should we chat about?
Does anyone have a decent place central we can gather (you're all welcome to come to our office in Aldgate East but it's a bit out of the way).

Thanks All!!

**Comment by Ankcorn** [comment]
I feel great about having an organisers Meetup next week.

I'm not available on Wednesday but can do any other day (I think)

**Comment by hewIngram** [comment]
Wednesday is JSMonthly right? I'm not available then either.

@lnug/organisers

**Comment by Ankcorn** [comment]
Tuesday is js monthly.

**Comment by seanmtracey** [comment]
Sounds good to me. Can't do Monday / Tuesday, but should be fine Weds/Thurs/Fri :)

**Comment by hewIngram** [comment]
I feel like theres probably some kind of poll tool that would make it really easy to organise this... anyone?

**Comment by Ankcorn** [comment]
I got you

👍  Monday
🎉  Tuesday
😄  Wednesday
🚀  Thursday
❤️  Friday

Now react to this post 😲

**Comment by hewIngram** [comment]
Love it - thanks Thomas!

**Comment by hewIngram** [comment]
I feel like theres some magic feature that would have alerted all the organisers that I've missed out on. Is there an LNUG equivalent of the bat signal @admataz ?

**Comment by Ankcorn** [comment]
@lnug/organisers - such teamwork 🤣

**Comment by admataz** [comment]
hey all @lnug/organisers  and @lnug/contributors  !! I put out a message on twitter too - that's what got you all interested. https://twitter.com/LNUGorg/status/1155854406996377600

tell your friends! 

I'm flexible this week or next - just need advanced warning

**Comment by simonmcmanus** [comment]
Im not in London much these days. I should be able to dial in any day of the week.   If its wed/thurs/fri i might be able to make it in person.

**Comment by seanmtracey** [comment]
Hey everyone, are we looking at meeting on the Friday? (Looking at Thomas's poll)

**Comment by Ankcorn** [comment]
Any thoughts on a location?

**Comment by seanmtracey** [comment]
Can do pub/restaurant somewhere around the Conde Nast offices? We all know how to get there :)

**Comment by Ankcorn** [comment]
That sounds like a fun plan! :) I know of a good and reasonably priced Japanese restaurant close by called Taro. Suggestions welcome though 👍

**Comment by seanmtracey** [comment]
I've been to Taro before, lovely place, works for me :)

**Comment by admataz** [comment]
ok - great. who else can make it tomorrow?

**Comment by jkbits1** [comment]
hi, it's been quite a while since I did any actual organising, but I'm in central London tomorrow and would enjoy attending. Any time from a little before 6 is fine for me.

**Comment by seanmtracey** [comment]
That works for me too. How does 18:30 work for everyone? Will that give everyone a chance to travel without too much of a rush?

**Comment by admataz** [comment]
@ankcorn. please can you post a link to the restaurant? 

see you there tomorrow !

**Comment by Ankcorn** [comment]
http://www.tarorestaurants.co.uk

The one on brewer street

**Comment by hewIngram** [comment]
Might be a bit later than 6:30 but I'm in!

**Comment by hewIngram** [comment]
Sorry! Got swamped and didn't get around the notes but... here they are:


- Talks table - a table to help first time speakers, especially from underrepresented groups, to help them flesh out talk ideas, and encourage them to submit talks. Who wants to run it? Maybe @admataz  + someone else is good for the first one (as Adam is well recognised)?

- Actively encourage people we think should be talking. A diversity of speakers will filter through to more diverse attendees. 

- Organise node core feedback @admataz (I'm happy to help)

- LNUG organizers more active on twitter

- Make something of the video archive we have. Tweet videos occasionally. Categorize video library

- Promote other groups at lnug: codebar, nodeschool.... others?

- Mid month workshop in September. Announce with the first newsletter?? 

- Setup lnug bank account @admataz 

- Let's be more picky with speaker bookings. And let's investigate a more diverse set of MCs

- Lightning talks?? How to arrange? Unconference? 

- Speaker buddies/meetup buddies? @BethGriggs would be cool to hear more about this.

- Maybe... Not pizza??? Investigate a different food option.

- Add other organizers to contact@lnug

**Comment by Ankcorn** [comment]
Thanks for writing these up!

**Comment by jkbits1** [comment]
Thanks, @hewIngram these are a great summary. Some terrific ideas for supporting under-represented groups in there

**Comment by admataz** [comment]
Thanks @hewIngram  - great to see you all too  - I 'm extra super excited about the possibilities and it's brilliant to have you all along with the organising! great job!

@hewIngram  - let's chat about a good approach to the node core feedback session and slot it in for this month's meetup... I'll open another issue for this. 

@Ankcorn  - saw your workshop issue - sounds great! let's do it!!! when the details are settled we can create an event on Meetup if that's useful.

**Comment by admataz** [comment]
Update from me: 
- I've thought about the node core feedback session but not done much about it - there's a comment in #28  with some thoughts about an approach - but happy to roll this over to Sept., 
- I've got an appointment at a bank about an account - but the lead time is 4 weeks, will update you on my thoughts when we meet.

**Comment by neshka** [comment]
Hey guys,

is it possible to meet during the weekend sometime?
I'm not able to join you during the week (Mon-Fri) for next/any organisers meetup.

Maybe I could do Fridays but around 7:30 earliest. 

Let me know what do you think :)

**Comment by hewIngram** [comment]
That would be awesome! I'm up for that but might be harder for folks with kids and stuff. But lets see

**Comment by Ankcorn** [comment]
We could try do a remote one next time?

Play drawful Or something like that?

🧐

**Comment by admataz** [comment]
I've extracted the relevant todos and will raise separate issues if neccesary for the remainders
