### ISSUE TITLE
LNUG #87 - August 28th 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#28]
@lnug/contributors @lnug/organisers
Who's going to be around to help in August? :)

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month?  @neshka 
- [x] Registration - this is all on Meetup now @neshka 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @neshka 
- [ ] Monthly Mailer (Mailchimp)
- [x] Slides (usually the MC) @neshka 

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues @neshka 
- [ ] Confirm Venue arrangements @admataz 
- [ ] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [x] MC/host @neshka 
- [x] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door
- [ ] Doors after 7pm - leave a contact number on a note
- [x] Jobs/recruitment table (@hewIngram )
- [x] Talk mentoring table (@admataz && @seanmtracey )
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## After the event
- [x] thanks to speakers @neshka 
- [ ] thanks to sponsors
- [x] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [x] duplicate this list for next month @neshka 

Anything else?

**Comment by admataz** [comment]
hi @neshka  - thanks for getting the todo list going for this month... how do you feel about taking on the MC duties this month? Let me know if you're up for it.

**Comment by neshka** [comment]
Hey @admataz, yes I could! I need to confirm with my manager if I can leave work earlier that day (I travel from outside of London) but I think it can be done :)

**Comment by admataz** [comment]
@hewIngram  - we spoke about running a node user feedback session... once again the month has caught up with me... here's the central discussion. 

https://github.com/nodejs/user-feedback/issues
https://github.com/nodejs/user-feedback/issues/115

and this: https://docs.google.com/document/d/129syiwgsn_doJ2TD9zRqjSRN8qZEW9xj0xwPcEXGaSc/edit

any thoughts? 

I think the outline in the doc is a little heavy for our format (recommended time 60mins? no thanks) it would be good to start off with a light "who's doing what" - get an overview of how our members are using node in what contexts - get a rough idea of who understands what about contributing to node and node's update cycle. May lay the groundwork for something like identifying specific issues. Give ourselves 10-15 minutes.

**Comment by admataz** [comment]
@lnug/organisers @lnug/contributors 

Who's around tomorrow to help. It's going to be a good night! Great talks - and looking like a full house.

**Comment by hewIngram** [comment]
I'll be there - can arrive earlyish to help setup and more than happy to run the jobs table.
@admataz and @seanmtracey  we should stagger it and the talks table maybe so people can get to both?

**Comment by admataz** [comment]
@hewIngram - yes I agree - let's stagger it.

**Comment by seanmtracey** [comment]
Works for me! I'm going to be a little late to this evening's LNUG, so if we do one after the other, I should be around in time to help with whichever table is second :)
