### ISSUE TITLE
LNUG #71 - March 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#3]
Hello @lnug/organisers and @lnug/contributors 

We have an amazing lineup of speakers for later this month... Get involved! 

Please have a read if the docs at https://github.com/lnug/event-planning  - and ask here in the comments if you have any ideas or questions. 

# Checklist (pick a task!)
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github  @admataz
- [ ] Who will emcee this month? @admataz
- [x] Registration - this is all on Meetup now  @admataz
- [x] Website updates  @admataz
- [x] Monthly Mailer (Mailchimp) @orliesaurus 
- [ ] confirm sponsorship arrangements  @admataz
- [ ] Slides (usually the MC)  @admataz

## Last day checks (Monday before event)
- [x] Confirm with Speakers  @admataz
- [x] Confirm Venue arrangements with Makers (or other venue if we ever move)  @admataz
- [x] Confirm Video with Pusher  @admataz
- [ ] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders  @admataz
- [x] Beer orders  @admataz

## On the Night
- [ ] MC/host  @admataz
- [ ] --- any special announements or ticket giveaways --- ? 
- [x] Ticket Scan/ Door @jkbits1
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] T-Shirts
- [ ] Twitter and tweeting @claireinez
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [x] activate next month's registration on Meetup
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [x] duplicate this list for next month

Anything else?

**Comment by orliesaurus** [comment]
MailChimp ready & ticked off

**Comment by admataz** [comment]
Thank you @orliesaurus  - I've edited to update the sponsors  - more info on that coming - but Tiro are bowing out, and we have new partners lined up and in discussion - which I will run past organisers.

**Comment by admataz** [comment]
![screen shot 2018-03-14 at 10 25 46](https://user-images.githubusercontent.com/395101/37396886-1b0abc22-2772-11e8-9e29-19982bf4c07c.png)

**Comment by admataz** [comment]
@lnug/organisers @lnug/contributors  - we meet on Wednesday...  who of you will be with us to help?

**Comment by FabioAntunes** [comment]
I will be there

**Comment by domfarnham** [comment]
I cannot make this one unfortunately. Parents evening this week.

Enjoy.

Dom

**Comment by thanpolas** [comment]
@admataz I can come, time and place?

**Comment by claireinez** [comment]
I'll be there! I've put my name against Twitter, as per usual. Also happy to receive pizzas but only if it doesn't involve putting my phone number on the door downstairs!

@thanpolas it's at the same place as last month, Makers Academy on Commercial Street. Doors open at 6.30pm 😃

**Comment by admataz** [comment]
Anyone here with good Sound Skillzz ? Getting the balance right on the mics is a challenge every month - and it would be great if someone can take it on as a task for the evening to adjust the settings to keep the feedback squeaks down as the evening progresses.
