### ISSUE TITLE
LNUG #88 - September 25th 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#30]
@lnug/contributors @lnug/organisers
Who's going to be around to help in September? :)

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? @admataz 
- [x] Registration - this is all on Meetup now @neshka 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @neshka 
- [ ] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues @neshka 
- [x] Confirm Venue arrangements @admataz 
- [x] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table
- [ ] Talk mentoring table
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## After the event
- [x] thanks to speakers @neshka 
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup @neshka 
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by seanmtracey** [comment]
Hey everyone, I won't be able to make this months LNUG as I'll be in Germany. Hope it all goes smoothly, and if there's anything I can help with in the run up, shoot it my way :)

**Comment by admataz** [comment]
thanks @seanmtracey  - have a great time in Germany! spread the word of LNUG where ever you go!

**Comment by Ankcorn** [comment]
Hey a bit off topic but it would be great to grab some time to discuss the
lnug workshop before next week's event.

I have found a potential host/sponsor so really it's up to whoever wants to
get involved what the workshop is about.

Im seeking to them on Thursday so it would be great to get some discussion
going in the GitHub thread before then
https://github.com/lnug/event-planning/issues/29

**Comment by leggsimon** [comment]
@seanmtracey !!!! In Berlin???

**Comment by seanmtracey** [comment]
@leggsimon Hamburg, but possibly Berlin at the end of the week. Let's try and figure out drinks when I know a bit more about my schedule 🍻

**Comment by admataz** [comment]
hello @lnug/organisers  - who's coming tomorrow?  - I've put myself as MC - but if anyone is up for it - please feel free - the mic is open if you want it.
