### ISSUE TITLE
LNUG #89 - October 23rd 2019

### ISSUE THREAD

**Issue by neshka** [lnug/event-planning#31]
@lnug/contributors @lnug/organisers
Who's going to be around to help in October?

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? @admataz 
- [x] Registration - this is all on Meetup now @admataz 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @admataz 
- [ ] Monthly Mailer (Mailchimp)
- [x] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues
- [x] Confirm Venue arrangements @admataz 
- [x] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table
- [ ] Talk mentoring table
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup @neshka 
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by hewIngram** [comment]
I'll be about - happy to MC if we need one?

**Comment by seanmtracey** [comment]
Argh, I'm out of town again this month :/ Sorry, I've been a bit useless lately, I'm gonna work on freeing up my calendar 😅

**Comment by admataz** [comment]
@hewIngram  - let's bounce the MC around on the night between us - keep it moving and light. We'll need to be strict with speakers on time - in a kind and fun way

**Comment by hewIngram** [comment]
Sounds like a plan!
