### ISSUE TITLE
LNUG #90 - November 2019

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#32]
@lnug/contributors @lnug/organisers

Almost everything in place, but never too late to start the list! Who's coming this Wednesday?

Choose a task...

# Checklist
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month? @seanmtracey 
- [x] Registration - this is all on Meetup now @admataz 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @admataz 
- [ ] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [ ] Confirm with Speakers via the github issues
- [ ] Confirm Venue arrangements @admataz 
- [ ] Confirm Video with Pusher @admataz
- [ ] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table
- [ ] Talk mentoring table
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [x] activate next month's registration on Meetup @neshka 
- [x] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube 
- [x] add those interested in joining lnug orgs
- [x] duplicate this list for next month @neshka 

Anything else?

**Comment by seanmtracey** [comment]
Hey everyone, I believe I volunteered to MC tonight at our last meeting, so I've whacked my name above. If anyone else was planning to do it, let me know and I'll happily withdraw :)

**Comment by admataz** [comment]
Hey @seanmtracey  - you're welcome to MC - but given you are also doing a talk - maybe someone else can pick up the mic for MC duties? 

@hewIngram ? @Ankcorn ? 

Also - whoever does it can you also do the slides?

**Comment by hewIngram** [comment]
I'll be about so happy to jump in as MC

**Comment by admataz** [comment]
video is now on our channel: https://www.youtube.com/playlist?list=PLam_80-FY3vRrbZMQYgxNuG4zdr7R8nhz
