### ISSUE TITLE
LNUG 2020 🎉 - let's do this!

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#33]
@lnug/organisers 

I hope you’ve all had a good break from it all. Today is my first day back at things…  a few things to work out.

We have a meetup planned for 22 Jan - a bit to do for that: 

- we need to look for a new venue - I think I shared with you all that Michelle at Conde Nast gave us a nudge  - they want to host some new meetups - it’s been a good time with them - but it’s time to move. They will still host us if we are stuck - but I at least want to try. I have made contact with Pusher, and Alpha Sights (based near Mansion House) via Alex our video guy - but if any of you have ideas - let’s discuss. 

- So far no speakers confirmed for January - we have [a proposal](https://github.com/lnug/speakers/issues/177)  - I’ve asked if the speaker is still available. But maybe put your minds to some ideas on that front. 

- Maybe time for another organisers catchup in the next week? 

- Have discussed the podcast with @simonmcmanus  - we're going to record a pilot episode this month. 

Please share this with anyone you feel would be keen to help organise…

**Comment by hewIngram** [comment]
A catchup sounds like a plan!

Do we need a venue for Jan?

For this months I was thinking it might be nice to have a retrospective-style 'Things I like about LNUG' and 'Things I don't like about LNUG' type thing to try to get feedback from attendees

**Comment by admataz** [comment]
yes, if we can find a new venue, that would be great - otherwise I will go cap in hand to Michelle - she said it would be ok - but I don't want to go back to Conde without even trying to find an alternative - seeing as they asked. 

an interactive session is a good idea - maybe an opportunity to do something fun to draw out some participation. 

How is your week looking?

**Comment by Ankcorn** [comment]
An interactive session sounds like good fun! 👍

A retro type thing would be very interesting.

I can try reach back out to depop and see if they are still onboard with hosting. We could try and arrange our organisers meetup to start with a little tour of the venue to see if it would be appropriate.

I'm at another meetup on tuesday night https://www.meetup.com/eXtreme-Tuesday-Club-XTC/events/wcwwmqybccbkb/ (XTC: Testing Shapes - Pyramids vs Henges)

But every other night is free for me

**Comment by hewIngram** [comment]
I'm pretty free this week I think - out Weds but other than that good.

**Comment by seanmtracey** [comment]
I should be able to do something towards the end of this week. 

Regarding the venue, could we put out a tweet asking people if there's anyone willing to host us? We should definitely include a big LNUG thank you to Conde for being so generous over the last few years if we do.

**Comment by admataz** [comment]
venue update: I've created a separate issue for this at #34  - and I've emailed a few of the people who have offered help over the last year or two - hopefully something comes of it - but please do keep a look out for something. 

@seanmtracey  - yes we will be sure to thanks Conde greatly - they have been fantastic hosts. 

Meeting this week - Thursday or Friday daytime is best for me - but can do early evening on Friday too if that suits everyone better.

**Comment by admataz** [comment]
Another update: 
I've had some response from the tweet I put out last night: 
- Beamery  - city/ finsbury based - I spoke to the guy at a recent meetup, and seems keen
- Will Morgan has volunteered a space in WeWork York Road (Waterloo)
- Powster have new offices in Hackney Wick (maybe a bit far out)

I'll contact Beamery with a view to visiting their space Wednesday or Thursday  - how does that suit everyone?

**Comment by Ankcorn** [comment]
I had a chat with Aris and he offered to reach out to some of the cityjs sponsors to see if they would be interested. Also his company Buildit by Wipro digital are interested.

We could do a lunch again?

Do we want to try and move around the city this year or do people think its better to have one venue?

**Comment by admataz** [comment]
Thanks @Ankcorn ! There are pros and cons, but - I think that we should try move around a bit - see how that goes. I like the idea of it in terms of including more hosts and circulating to other spaces - which can also help draw different people to the events. It's worth a try anyway. We have been a bit exclusive with Conde because it's so nice - but it's also meant turning offers of help away. 

Lunch suits me  - shall we say Thursday? - venue TBC (waiting to hear back from Beamery - mayby we can combine a city/spitalfields lunch in the area)

**Comment by seanmtracey** [comment]
Thursday lunchtime works for me too :)

**Comment by hewIngram** [comment]
Beamery are at Moorgate right? I've been to a meetup hosted there before and it was a decent space. 
Ozone isn't too far away and is nice. Shall we tweet out an open invite in case anybody is up for getting involved as an organiser?

**Comment by admataz** [comment]
Today's update: 
### 1. Venue and lunch: 
I'm meeting Milo Abel at Beamery tomorrow (Thursday) from 12:00-12:30 - she's going to show me around. Who would like to join us - and then we can get lunch and discuss plans after that? 

### 2. Twitter and accounts
I've made a start at cleaning up our organisers accounts etc - you should have received an invitation to the [@LNUGorg](https://twitter.com/lnugorg) team collaborator account thingy - so we can avoid needing to share the same login (I didn't even know this was possible !) 

I'll also look at thinning out the accounts with privileged access on github - those we haven't seen or heard of in the last year. 

Venue suggestions in the Moorgate area for lunch tomorrow?

**Comment by hewIngram** [comment]
Happy to join tomorrow for Beamery!

**Comment by seanmtracey** [comment]
Ditto!

Re. Venues for lunch in Moorgate: The Tokenhouse is pretty good, and usually not too busy around lunchtime. It's ~5 minute walk from either Moorgate or Bank tube station.

**Comment by admataz** [comment]
Great - let's meet outside [WeWork at 131 Finsbury Pavement](https://www.google.com/maps/place/WeWork+131+Finsbury+Pavement/@51.5201758,-0.0897586,17z/data=!4m12!1m6!3m5!1s0x48761cac021505cf:0xbb962e52290d79f9!2sWeWork+131+Finsbury+Pavement!8m2!3d51.5201758!4d-0.0875699!3m4!1s0x48761cac021505cf:0xbb962e52290d79f9!8m2!3d51.5201758!4d-0.0875699) tomorrow at about 11:55 - apparently we all need to check in and get badges. Anyone else joining us? I'll let Milo know who's coming.  Then we can go for lunch at The Tokenhouse - sounds nice.

**Comment by admataz** [comment]
My number - if anyone's delayed or lost is 07757234443

**Comment by Ankcorn** [comment]
I might not make it, we are interviewing somebody 🎉and I'm not 100% certain of the schedule and who is doing what yet.

**Comment by seanmtracey** [comment]
Hey all, not going to be able to make the Beamery meet in time (buried in post-holiday emails atm), but should still be able to make the Tokenhouse meet. Will keep updated :)

**Comment by admataz** [comment]
Quick follow up from our earlier meeting: 

- Beamery have confirmed - we're on for the 22nd
- Let's get details for the event finalised - I've created a talk proposal for the retro - let me know if you want it different - or make another? 
- Maybe space for another lightning talk  - any preferences ideas, speakers? 

There's more we discussed - I'll try summarise more tomorrow. !

**Comment by admataz** [comment]
in closing this issue - I think it's worth mentioning and high fives all round in how much we achieved this month - let's meet again soon and keep up the organiser momentum. 

Thanks all.
