### ISSUE TITLE
LNUG #91 - January 2020

### ISSUE THREAD

**Issue by hewIngram** [lnug/event-planning#35]
@lnug/contributors @lnug/organisers

Realised we were still after one of these!

Choose a task...

# Checklist
## Pre Event
- [x] Find/confirm a vanue
- [x] Find/confirm speakers! and add them as contributors to github 
- [x] Who will emcee this month?
- [x] Registration - this is all on Meetup now @admataz 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @admataz 
- [x] Monthly Mailer (Mailchimp)
- [x] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers via the github issues
- [x] Confirm Venue arrangements @admataz 
- [x] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [x] MC/host
- [x] --- any special announements or ticket giveaways ---
  - [x] Raffle a ticket to REact Amsterdam
  - [x] give a big push for CityJS conference
- [x] Ticket Scan/ Door
- [x] Doors after 7pm - leave a contact number on a note
- [x] Jobs/recruitment table
- [ ] Talk mentoring table
- [x] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [x] Receive Pizza
- [x] Food & Drink Area Maintenance (keep the cold beer rolling!)

## Venue questions - checklist
- [ ] What’s a good time for us as organisers to arrive and help with set up?
- [x] do you have a tub for the drinks? 
- [x] We’ll need to get ice on the night
- [x] there are a couple extra non alcoholic and alternative drinks I will order for delivery from Ocado - I will try arrange for this after we arrive @admataz 
- [x]  just confirming - there will be a table space to lay out the pizza? I’ll try get it in two deliveries 6:30 and 7:40
- [x] For cleaning up during the night and after - I can order black bags etc - but can you confirm what we should do with all the rubbish, is there a recycling place for us to leave stuff. 

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [ ] activate next month's registration on Meetup @neshka 
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by admataz** [comment]
Milo from Beamery has suggested the pub for drinks after: http://singertavern.com - looks good

**Comment by seanmtracey** [comment]
Thought that looked familiar, it's my bolt hole after a long day! Good place, great range of beer, plenty of space.

**Comment by hewIngram** [comment]
Do we have an MC?

Also: I can get there early is anything needs doing - just let me know.

**Comment by admataz** [comment]
MC  - I'm happy to do it if there's no one else keen...  let me know

**Comment by admataz** [comment]
For whoever MCs - here's a proposed running of events for the evening - I feel a little nervous because new venue, and different kind of programme - so many moving parts!  @hewIngram  - let me know how this fits in time/space wise for the interactive session you will be coordinating: 

```
6:30 - people start arriving - we should have pizza and beer ready 
7pm  - introduction and welcome - and announcements - this is a good time for Beamery to have a quick hello
7:10 - Rob’s talk
7:50 - quick review of out plans for the second half, which is an interactive session @hewIngram  will be running, looking back/ looking forward to 2020
7:55 - break for more pizza and beer  (will try arrange a second delivery) 
(jobs table and postit posting in the break?) 
8:15 - 2020 retro buzz session starts
8:45 -  nodewatch demo (@admataz) 
8: 55 - react summit ticket draw
9:00 - windup and packup and to the pub

```

**Comment by hewIngram** [comment]
I think we maybe leave retro-related stuff until the session after the break. I think trying to do much after Rob's talk might not work (although I appreciate getting people up and down again is annoying).

I might try to get a bunch of people to scribble down three words that describes LNUG before we start and in the break and then have the retro session being:

Quick intro about the year that was (and some fun stats). A little about how LNUG happens (and a call for anybody who wants to get involved as an organiser). A short thing about what a retro is and how we're going to do a kind-of-retro. Review the sets of three words that people had as a kind of starter exercise.
Then station 4 of us in corners with postit notes and sharpies and send people to do some scribbling.
Then bring everyone back for a little conclusion (maybe plug more workshops and the podcast idea)

**Comment by seanmtracey** [comment]
![MVIMG_20200122_203842](https://user-images.githubusercontent.com/913687/72997424-43fa1980-3df4-11ea-8d8d-28cb788e96f9.jpg)
![MVIMG_20200122_203818](https://user-images.githubusercontent.com/913687/72997425-43fa1980-3df4-11ea-8974-95a13050ca05.jpg)
![MVIMG_20200122_203755](https://user-images.githubusercontent.com/913687/72997427-4492b000-3df4-11ea-834b-db31344bd84b.jpg)
![MVIMG_20200122_203739](https://user-images.githubusercontent.com/913687/72997429-4492b000-3df4-11ea-8223-58136da005c8.jpg)

Photos of the feedback boards added for future reference.

**Comment by seanmtracey** [comment]
I have no idea why they're upside down 😅

**Comment by leggsimon** [comment]
![upsidedown](https://user-images.githubusercontent.com/11544418/72998388-07cbb680-3dfe-11ea-83e1-9466c10ccb45.gif)
