### ISSUE TITLE
LNUG - Workshop #2 - 4th March 2020

### ISSUE THREAD

**Issue by Ankcorn** [lnug/event-planning#36]
Theme: Create an LNUG Talk Proposal

LNUG is your local friendly Node.js user group, inspired by [GDCFP](https://www.globaldiversitycfpday.com) short for Global Diversity Call for papers day. We are running a LNMTPE. (too many acronyms? 🤣 okay here's what we plan to do)

We the LNUG organiser team and volunteers will be here to help you plan, and submit your first meetup talk.

Everyone is welcome, we love new speakers, old time speakers, people with experience from different industries. Anecdotally the best time to talk about something is just as you learn it.

Driven by the roaring 🦁 success of of our first workshop the "Christmas Node Mini Hackathon
" we are really excited to try the same thing again.

The format will be.
6.30pm arrive - socialise, food!
7pm kick off - Very short Introduction to LNUG, the format, and lightning talk on what it's like to talk at LNUG
7.15pm - Pair up and start working on a talk proposal.
8.45pm - Get together as a group and share our talk proposals & schedule anybody's proposal for a future LNUG if they want too
9.00pm - Pub - Prince Arthur

Looking forward to seeing you there 😊

Venue: NearSt
Food: (TBC)
Drinks: NearSt

**Comment by admataz** [comment]
awesome! great idea

**Comment by admataz** [comment]
@Ankcorn - I love it that we are starting to run more varied events and concurrently to the regular meetups - thank you for this!

I will leave it to you to create the relevant details in meetup.com etc? 

Also let's get some twitter activity around this event 

Raises a couple issues - our website only really accommodates a single event at a time - and even then all the detail gets lost when the next ones come in.  @simonmcmanus  - let's talk about this in the context of a website refresh in the near future. (will create an issue on the website repo for this)

**Comment by Ankcorn** [comment]
Thanks @admataz

I will start to get the word out.

On the website I agree, it would be awesome to have a filtered view of what's on GitHub. It could be a good way to get people to participate in organising

**Comment by hewIngram** [comment]
This is exciting Tom! I'll pop along - let me know if theres anything I can help with or prep before hand.

**Comment by Ankcorn** [comment]
Thanks! Currently the only thing troubling me is drumming up a good croud. If everybody could share to their circles and appropriate places that would be amazing 🤗
