### ISSUE TITLE
LNUG #92 - February 2020

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#37]
@lnug/organisers 

We are two weeks away - and I'm pleased to say we have a venue!

@Ankcorn and @admataz went to visit yesterday - and looks really nice

[TotallyMoney](https://www.totallymoney.com/) 

```
Chapter House 
16 Brunswick Place 
London 
N1 6DZ 
```

We are still in need of another speaker - so please ask aroun. 

Choose a task...
# Checklist
## Pre Event
- [x] Find/confirm a vanue
- [x] Find/confirm speakers! and add them as contributors to github 
- [ ] Who will emcee this month?
- [x] Registration - this is all on Meetup now @admataz 
- [x] Website updates @admataz 
- [ ] Create Meetup event (copy last month) @admataz 
- [ ] Monthly Mailer (Mailchimp)
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [ ] Confirm with Speakers via the github issues
- [ ] Confirm Venue arrangements @admataz 
- [x] Confirm Video with Pusher @admataz
- [x] Pizza orders @admataz
- [x] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
  - [ ] give a big push for CityJS conference
- [ ] Ticket Scan/ Door
- [ ] LNUG organiser on the Doors and for after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table
- [ ] Talk mentoring table
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## Venue questions - checklist
- [ ] What’s a good time for us as organisers to arrive and help with set up?
- [ ] do you have a tub for the drinks? 
- [ ] We’ll need to get ice on the night
- [ ] there are a couple extra non alcoholic and alternative drinks I will order for delivery from Ocado - I will try arrange for this after we arrive @admataz 
- [ ]  just confirming - there will be a table space to lay out the pizza? I’ll try get it in two deliveries 6:30 and 7:40
- [ ] For cleaning up during the night and after - I can order black bags etc - but can you confirm what we should do with all the rubbish, is there a recycling place for us to leave stuff. 

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup @neshka 
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by admataz** [comment]
⭐️ 🌟 
@lnug/organisers @lnug/contributors  - can you press gang your friends/workmates/ for a second talk  - or a couple lightning talks for next week? It would be good to fill up the schedule...

**Comment by admataz** [comment]
ping! anyone? Otherwise you'll get me for a 3rd LNUG running 😁

**Comment by Ankcorn** [comment]
pong! I can mc ☺️ 

It's also super easy for me to get there early and do any setup required.

**Comment by admataz** [comment]
excellent! @Ankcorn is our MC for the night!!

**Comment by Ankcorn** [comment]
If anybody has anything to add to the slides let me know

**Comment by admataz** [comment]
@Ankcorn  just to ping Aris and ask if there's anything specific to CityJS Conference he'd like to promote.
