### ISSUE TITLE
Assorted LNUG event ideas

### ISSUE THREAD

**Issue by hewIngram** [lnug/event-planning#39]
Tonight was awesome, I think there was some super interesting ideas being discussed. I'd love to kick off a thread to record those ideas while they're fresh.

Some key ones that I remember:
- More lightning talks!
- Content aimed at raw Node.js use cases (building a http server, cli tool etc)
- More interactive short talks
- The idea of hot tip/series of talks (cc @leggsimon - gone but not forgotten)

And like a billion other things that I didn't have the foresight to note down. Lets collect them in this issue and then we can prioritise and try some things!

Thanks all

@Ankcorn @seanmtracey @admataz

**Comment by admataz** [comment]
thanks all for the discussions - I really enjoyed this evening. My list of lightning talk ideas that I rattled through earlier (some of which are mentioned above). Anyone who wants to take these up... or if you have a discussion with a potential speaker who's looking for a topic... 
 
-  **naked node.js** - no dependencies, no express. no leftpad. getting value and understanding from core modules. could be a serialised talk topic module by module every other month or something
-  a quick guide to writing **command line programs** and custom tooling with nodejs
-  a quick introduction to **svelte and sapper** (we may have this covered - I've been speaking to Antony from the Svelte meetup)
-  **streaming experiments** and failures - I had some broken code somewhere which may fit into the naked nodejs topic above. 
-  a quick overview of the **web framework ecosystem** - hapi, express, fastify, sirv, polka… this could fit with our discussion on pitching talks to the 50% that are new to node in the audience
-  the **culture of javascript** - what makes this hacky language attractive to designer/developer/web creative oddballs. And oh, let's bring back the fun on the web. Glitch.com, and the spirit of geosites, etc. 
-  **levelDB** and the node frame of mind (I didn't mention this one earlier - but it's here on my list)
- **IPFS** and the future of networking - I will reach out to those I know and try to convince them to enlighten us at LNUG with a talk(hello @olizilla and @alanshaw? did you hear your name mentioned 😄 )
- @seanmtracey mentioned his electronic js controlled bagpipes - but I'm in favour of any JS controlled hardware hacks and musical instruments (not sure about bagpipes)

**Comment by admataz** [comment]
I'm cleaning up old issues and closing old discussions like this - I still like some of these ideas discussed above - hopefully with our restart we can get to some of them.
