### ISSUE TITLE
LNUG #93 - 25th March 2020

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#40]
@lnug/organisers 

So all going well and we aren't on some lock down or ban on public gatherings - we have a meetup to arrange on 25th March. 

I've confirmed a venue with Trussle - it's a little smaller than we are used to - but it's a nice space. 

<address>
 1-3 Dufferin St, London EC1Y 8NA
</address>

[Trussle Mortgages: Free Mortgage Advice & Broker](https://trussle.com/) 

## NOTE ABOUT HYGIENE - COVID-19 - CORONA, ETC. 
I've had some people ask about how we are planning to take responsibility for hygiene on the night - if I can get hold of some I will get some hand sanitiser to be available at the door and on tables - but here seems to be specific anxiety around shared food and pizza specifically - and a suggestion that we should be looking at something closed, and not open/shared. 

As it happens - this month Trussle want to cover food and drinks this month - so it's less in our hands (no pun intended) but  I will discuss with the hosts. 

Anyone have any thoughts or ideas they'd like to add? 

## Otherwise... 
We are still in need of another speaker - so please ask around. 

## Pre Event
- [x] Find/confirm a venue
- [x] Find/confirm speakers! and add them as contributors to github 
- [ ] Who will emcee this month?
- [x] Registration - this is all on Meetup now @admataz 
- [x] Website updates @admataz 
- [x] Create Meetup event (copy last month) @admataz 
- [ ] Monthly Mailer (Mailchimp) @admataz
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [ ] Confirm with Speakers via the github issues
- [ ] Confirm Venue arrangements @admataz 
- [ ] Confirm Video with Pusher @admataz
- [ ] Pizza orders @admataz
- [ ] Beer orders @admataz

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
  - [ ] give a big push for CityJS conference
- [ ] Ticket Scan/ Door - we need someone from LNUG to let people in
- [ ] LNUG organiser on the Doors and for after 7pm - leave a contact number on a note
- [ ] Jobs/recruitment table
- [ ] Talk mentoring table
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Receive Pizza
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!)

## Venue questions - checklist
- [ ] What’s a good time for us as organisers to arrive and help with set up?
- [ ] do you have a tub for the drinks? 
- [ ] We’ll need to get ice on the night
- [ ] there are a couple extra non alcoholic and alternative drinks I will order for delivery from Ocado - I will try arrange for this after we arrive @admataz 
- [ ]  just confirming - there will be a table space to lay out the pizza? I’ll try get it in two deliveries 6:30 and 7:40
- [ ] For cleaning up during the night and after - I can order black bags etc - but can you confirm what we should do with all the rubbish, is there a recycling place for us to leave stuff. 

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] activate next month's registration on Meetup @neshka 
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video  from Pusher and upload to YouTube 
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month @neshka 

Anything else?

**Comment by beauallison** [comment]
Venue Checklist Items
- Arrival about 30~ minutes before should be more than enough time to setup 
- We will have a fridge nearby on the night, no need for a tub or ice
- We have rubbish bags available, @yannislionis can direct on the night but we will take care of putting rubbish away
- We will have tables available for any food / beverages

**Comment by hewIngram** [comment]
So.... LondonCss was remote last night and by all reports (i.e. @leggsimon on twitter and @Ankcorn ).... thoughts? Pretty sure we could ask Oliver at LondonCss for advice if needs be.

My whole company has gone remote so presumably others are and attendance will be down if we go ahead in person.

**Comment by admataz** [comment]
thanks @hewIngram  - yes - it's looking more and more that way... and it is starting to feel like it's impossible to sift out the FUD - and it could be considered irresponsible  at this point to go ahead with an in person meetup event. We have about 63 people signed up  - but I don't know how many of those are optimists  like me :) . I think you're on the email list that included cameraman Alex's suggestions - and offer of help to live stream (not sure if he was involved with LondonCSS). So we should start considering that and talk to him about what's entailed. I'm happy to wait till after the weekend before making a decision on this. 

 @beauallison @yannislionis  - do  you have any updates from your office that may supersede this? i.e. is Trussle considering closing offices at all?

**Comment by admataz** [comment]
@lnug/organisers 
It probably comes as no surprise that we have had confirmation from our hosts at Trussle that they will not be able to host. We should start thinking about whether we want to do this remotely. 

Please add your thoughts here

**Comment by hewIngram** [comment]
Definitely for the best!

Oliver shared this as how he did LondonCss: https://dev.to/_phzn/running-my-first-online-meetup-o1h

**Comment by hewIngram** [comment]
Oh wait - I know that face.
@seanmtracey reckon we can rope Kevin in to give us a hand? I've used OBS a bit but definitely not proficient

**Comment by Ankcorn** [comment]
I was literally about to post kevins article! @phazonoverload 

Its very good, I think it could be a super fun challenge to host an online meetup. I am familiar with OBS (from my league of legends days). But have not configured something with as many scenes as that.

With some preperation I think we can make a huge success

**Comment by hewIngram** [comment]
Dat username...

"from my league of legends days" - we need to talk about this at some point @Ankcorn 

Yeah I think it'll work fine. Just needs a little prep

**Comment by seanmtracey** [comment]
That reminds me, how do we get @phazonoverload on the organisers mailing lists etc?

**Comment by phazonoverload** [comment]
Hiya! I'm now a LNUG organiser so I'm happy to do all the work related to taking the event online. External to me, we need:

* A place to host - Twitch/YouTube Live account
* Moderators for chat - I would prefer not to do this if I'm operating the stream
* A video call for all the speakers - Hangouts/Skype/Vonage meetings ;) 
* Ideally one MC
* Graphics for the various part of the stream. I am happy to sort these

If you want to do it still, I'm down.

**Comment by Ankcorn** [comment]
![lnug](https://user-images.githubusercontent.com/7361428/76771671-9d008100-6797-11ea-8a15-48526a92498d.png)
I have made a square lnug logo with a dark grey background for the stream. Will this work

**Comment by phazonoverload** [comment]
Give me whatever you have and I'll make it work. 

EDIT: got just the logo on a transparent BG?

**Comment by Ankcorn** [comment]
I was going to get it printed as lnug stickers :P its quite low res so I might create a bigger one in a this evening

**Comment by admataz** [comment]
@Ankcorn  - will anything [here](https://github.com/lnug/resources/tree/master/logo) help you ? 

https://github.com/lnug/resources/tree/master/logo

**Comment by hewIngram** [comment]
Super happy to moderate obvs.
@admataz do you have the logins for: https://www.youtube.com/channel/UC-qjgj2TnRoI1ZmFFaN3FeQ
Would be sensible to use it for the live stream - happy to investigate if you can send over the logins

**Comment by admataz** [comment]
@hewIngram  - it's all 2fa - can you confirm a google account you can use and I'll add you as a contributor? I think that will work

**Comment by hewIngram** [comment]
Fo sho: hew.ingram@gmail.com

Thanks! (also while we're here - the Hew Ingram that is an admin on the meetup page is an old account I don't have access to - if someone can switch to hew.ingram@gmail.com that'd be cool)

**Comment by admataz** [comment]
@hewIngram  - added you to YouTube - let me know if you have any trouble. 
For meetup - I assume it's this account, and not some imposter with your name?! 
https://www.meetup.com/london-nodejs/members/239196087/

**Comment by hewIngram** [comment]
Yeah it's that one. I had another meetup account with my old Gousto email for some reason which is the one that was added before.

**Comment by Ankcorn** [comment]
Any time @hewIngram, 

It looks like we need to find some speakers, I might have found a good one. Just waiting on him to submit it.

**Comment by admataz** [comment]
Hello everyone. 

my update: 
I've updated the meetup page and messaged attendees. Also let Sam the pizza guy know there will be no event. Our one speaker has pulled out - so if we are going ahead with the online event we need to line something up. I'll put out a call on twitter - but let me know if anyone has ideas. 

Would like to get the details on how we run this finalised asap  - @hewIngram @Ankcorn @phazonoverload  - I'm leaving the logistics to you? Can you let me know if I need to do anything? 

Thanks!!

**Comment by hewIngram** [comment]
Yup - the only thing looking at using Youtube Live is that I don't get that option on the LNUG channel - not sure if it's permissions related.

Screenshots of mine vs LNUG:

<img width="1605" alt="Screenshot 2020-03-18 at 12 15 58" src="https://user-images.githubusercontent.com/17004905/76959823-47041880-6912-11ea-8d7d-c3e4aba432f8.png">
<img width="1605" alt="Screenshot 2020-03-18 at 12 15 51" src="https://user-images.githubusercontent.com/17004905/76959828-4bc8cc80-6912-11ea-85b4-965307738f7e.png">

Do you see the "Go live" option if you go to that page @admataz - can you escalate my privelages?

**Comment by Ankcorn** [comment]
A colleague has built an opensource library for email templating and its
super nice. I really want him to do a talk about it

Thomas

**Comment by phazonoverload** [comment]
If you can get a stream key for me from YouTube/Twitch, let speakers know that we'll run the event through Google Hangouts (& I'll want to test with them half hour before the event), and elect one person to be the MC, then I'm happy to sort all stream logistics and don't need much from anyone else :) 

What time are we aiming to go live?

**Comment by Ankcorn** [comment]
I watched serverless london meetup online last night and it did pre recorded talks, the format was not as engaging or interesting as london css. I think the live nature of londonCSS had a lot of value.

**Comment by admataz** [comment]
@hewIngram - damn - I guess when they say "can add anything" they don't really mean it. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/395101/76962492-3efaa780-6917-11ea-84a8-1084a1c7af9e.png">

@phazonoverload  - as the owner I can set up a stream and share keys with you, is that right? (never done this before). If I set this up now as a stream starting at 18:30 on Wednesday 25th - will that give you enough to test? 

I'm rummaging through the LNUG bag of goodies, and find we have an `elgato hD60` capture thingy (https://www.amazon.co.uk/Corsair-Capture-Gameplay-Sharing-Playstation/dp/B00MIQ40JQ) Is this useful at all for what we are doing?

**Comment by phazonoverload** [comment]
All I’ll need it a stream key for on the day. That timing is fine.

**Comment by Ankcorn** [comment]
How many talks do people think are appropriate?

Also, I think it would be awesome to continue some of the social things that make lnug really fun to be apart of. We could start a zoom call between the talks, the free tier supports up to 100 people. Doing our jobs table and giving people a way to socialise could be nice.

**Comment by admataz** [comment]
@Ankcorn - I think up to 3 talks is good - and I agree - I'd love to continue the social aspect as much as possible. Zoom have a breakout function which could be interesting - I'm just wary of getting people to switch streaming platforms - can Zoom work for the streaming @phazonoverload ? I can ask at NearForm about using a pro account (no guarantees). Or does can we do something with google meetings? 

also @phazonoverload  - how can I contact you securely to share stream keys etc.

**Comment by bernardbaker** [comment]
Hi everyone,

Joining the conversation...

**Comment by phazonoverload** [comment]
If we’re going to use Zoom then I’m not required. My personal feelings are that we SHOULD move platforms between socials and talks - with talks happening on twitch or YouTube as the lowest barrier option. 

Let me know what you think and I’ll write a little primer this weekend on how it should all work.

**Comment by Ankcorn** [comment]
Ah @phazonoverload I think we might have got our wires crossed, even if we use zoom I imagine we would still want it to be streamed.

The primer sounds like a great idea, if you need any dummies to test it out on I am happy to be of service!

**Comment by phazonoverload** [comment]
Here is the plan:

We will handle the speakers through a Google Hangout. Only speakers, me, and the MC will be in this call. This group will also have a private chat going on a platform (probably WhatsApp). We will ask the speaker to keep an eye on this as it is our means of communication with them.

For streaming, we can use Twitch or YouTube Live. I've honestly had better success with getting an audience to Twitch streams, so I would encourage that. Either is fine though. I will build the slide layouts incl web captioning this weekend.

At 6pm we will enter the call, test with each speaker. At 6:25pm I will put the stream live with a holding slide, and then live at 6:30pm sharp. 

I would recommend no break in-between (just a couple of mins of MC talking so people can go to the loo), but instead, just have a session afterward. This session can be in a Discord, Slack, just using a conference call. Whatever works - but I'll leave that for you to decide. All I need is the link. 

Action points:

- [x] Kevin to design graphics
- [x] Decide who MC will be 
- [ ] Introduce me to speakers
- [x] Decide Twitch vs YouTube Live
- [ ] Make sure Kevin has access to the streaming platform
- [ ] Decide on post-event social space and communicate to Kevin

All low-key, all easy.

EDIT: Having seen the uptake on the YouTube channel I changed my mind and think we should use it. Could I get access to the YouTube channel? Will be easier.

**Comment by phazonoverload** [comment]
<img width="924" alt="Screenshot 2020-03-20 at 21 40 49" src="https://user-images.githubusercontent.com/1461554/77208456-c0a72c80-6af3-11ea-9737-e934a2736ffa.png">

<img width="943" alt="Screenshot 2020-03-20 at 18 37 23" src="https://user-images.githubusercontent.com/1461554/77208472-c735a400-6af3-11ea-9b79-54eb206913ef.png">

Where the slack URL is where we'll push them after the event.

**Comment by Ankcorn** [comment]
Twitch is more fun than youtube, they have great emoji's. Thanks for doing all this work @phazonoverload. Truly a heroic effort!

The only chat thing we currently have is https://gitter.im/lnug/discuss it's not very active

**Comment by phazonoverload** [comment]
I've built an online social space (for events generally) that we can use for after this meetup.

https://cafe.lws.io/#/lnug

Let me know what you think. I'm trying to emulate the act of moving around multiple smaller groups with a drink to have convos. I've created 3 'tables' but can create more.

**Comment by Ankcorn** [comment]
Dude, that is amazing! It's such a good idea

**Comment by admataz** [comment]
thank you @phazonoverload  - looks great - can you add a room for "Jobs Table" 

Also, can we make sure an LNUG organiser is assigned to each room? 

What access do you need for YouTube? I can make you a manager, and can set up the Live Video stream for you. What's your Google ID? And can you provide me with a secure way to share the streaming details with you? 

Many many thanks

**Comment by hewIngram** [comment]
This is super cool.
I'll be about on the night and can help with whatever - shall we schedule in 20 mins at some point to give everything a test run (if that hasn't been done already)

Do we have an MC yet? Might be nice coming from you @admataz given you're probably the face of LNUG to most. But happy to do it if it's needed.

**Comment by admataz** [comment]
@phazonoverload  - I have set up a scheduled stream on the LNUG youtube channel - send me your details and I can add you as a manager to the channel. 
The url is: https://www.youtube.com/watch?v=VV9-pLz_6Bo

I've introduced you to speakers in the relative talk proposal issues - let me know if you need further help coordinating: 
https://github.com/lnug/speakers/issues/187
https://github.com/lnug/speakers/issues/186

@hewIngram  - I'm happy to MC, no probs. 

Let's try a test run tomorrow (Tuesday). Let me know when suits you.

**Comment by hewIngram** [comment]
I'm easy to test tonight or some time tomorrow if @phazonoverload is game?

**Comment by bernardbaker** [comment]
Happy to test as well.

Regards,

Bernard T. A. Baker

**Comment by phazonoverload** [comment]
Hi! Just saw this, sorry. I can test this at 8pm. 

Use https://meet.google.com/dvh-kmao-ntc and we can talk it through, and then test it. I only really need one other person - Hew? - but happy for others to join.

**Comment by bernardbaker** [comment]
I'll take a seat.

I'll get in touch tomorrow.

Regards,

Bernard T. A. Baker

**Comment by phazonoverload** [comment]
We'll test at 6pm tomorrow with speakers. @Ankcorn and @hewIngram feel free to join the test call but during the event you don't need to be on it - just Adam, speakers and myself. 

If you both can look after moderating the YouTube chat, and pass any good questions to Adam and I to raise at the end if there's time.

Post-event we'll go to the social cafe app I built, but we really want at least one of us on each table for about 30 mins after the event. 

Adam can take table 1
Hew can take table 2
I'll take table 3
Thomas you can take table 4

If I can get access to our internal gitter chat I would be more thankful. Let's all be keeping an eye on this throughout in case there are any logistical internal conversations we need to have quickly. 

Cheers all!

**Comment by admataz** [comment]
Thanks @phazonoverload  for the test run through the set up earlier - and getting all this going. 

I've created a private channel in gitter for us to maintain a backchannel during tomorrow's event. 

[![Gitter](https://badges.gitter.im/lnug/streaming-backchannel.svg)](https://gitter.im/lnug/streaming-backchannel?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

@bernardbaker, @tschoffelen,  @hewIngram, @seanmtracey, @Ankcorn 
keep this open in a tab somewhere during the event!

**Comment by seanmtracey** [comment]
Hey everyone, I'm trying to grant permissions to the Gitter application, but it wants read + write access to the IBM public + private repos, which I'm not allowed to grant, but can't see an option to disable in the auth flow. Is there an something I'm missing / an alternative auth flow I can follow to get access without granting those rights?

**Comment by hewIngram** [comment]
WEIRD - I feel like I wouldn't have allowed it access to anything hmmmm

**Comment by seanmtracey** [comment]
![access](https://user-images.githubusercontent.com/913687/77568903-48f54b00-6ec1-11ea-9dc5-66d130003d00.png)
Yeah, I nearly clicked through w/o reading, but did a double-take when I actually took a second to look. This is what I get.

**Comment by bernardbaker** [comment]
Can someone send me the URL please?


Regards,

Bernard T. A. Baker

**Comment by seanmtracey** [comment]
@bernardbaker, I believe it's this one https://meet.google.com/dvh-kmao-ntc. @phazonoverload can you confirm?

**Comment by admataz** [comment]
@seanmtracey  - I'm looking into it

**Comment by hewIngram** [comment]
Massive thank you to @phazonoverload for all his help making this happen. It was awesome. And to @admataz for stepping up and MC-ing and @bernardbaker and @tschoffelen for wonderful talks.

👏 👏 👏 👏 👏 👏 👏

**Comment by bernardbaker** [comment]
Thoroughly enjoyed the entire event.

**Comment by tschoffelen** [comment]
It was fun! Thanks for organising it everyone!

**Comment by admataz** [comment]
@seanmtracey  - just an overdue follow up to the question about gitter - I found this -does it help answer any concerns? 

https://gitlab.com/gitlab-org/gitter/webapp/-/blob/develop/docs/oauth-scopes.md#github

will ping you over twitter too
