### ISSUE TITLE
LNUG #94 - 22 April 2020 - remote edition part 2

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#41]
Hello @lnug/organisers  - I hope you are all well? 

This month’s meetup is still on my calendar - and that’s less than 2 weeks away. We have no speakers lined up so far, so let's see if we can rustle up a few lightning talks for another remote session on the 22nd April…

As we are still in lockdown and  100% remote - we could take a talk from anyone in the world. 

### The adjusted-for-remote todo list
- [ ] confirm a couple talks
- [ ] arrange and confirm streaming/remote set up requirements for this month
- [ ] update meetup page
- [ ] update website
- [ ] who will MC this month? 

Will update this todo list more as the tasks for the event become clearer (special announcements, etc) 

Please add your ideas, thoughts, concerns to the comments

**Comment by orliesaurus** [comment]
Interested in hearing about the streaming/remote set up for this upcoming session

**Comment by phazonoverload** [comment]
I've refined the setup since the last LNUG meetup to ensure I get full control over speaker audio (and can mute it until it's their turn), which was the issue with March's meetup. I'm happy to facilitate the technical parts (using Skype, as my new setup requires), and have just put the event in my calendar. We can use Social Cafe again too if you want.

If you're short on speakers I can do one about using Airtable as a database, but not sure if it's boring?

**Comment by orliesaurus** [comment]
Is there a reason why you didn't go with Zoom ?

**Comment by phazonoverload** [comment]
Skype supports NDI in a feature they call [Skype for Content Creators](https://www.skype.com/en/content-creators/). Zoom, and others, do not. 

It’s this feature which allows us to isolate each video/audio stream inside of OBS (the software used to stream).

**Comment by orliesaurus** [comment]
Gotcha, thanks for the explanation!

**Comment by phazonoverload** [comment]
@admataz with a few days to go until this event I’m just checking if we’re still going ahead?

**Comment by admataz** [comment]
Hey @phazonoverload  - thanks for chasing... I was thinking the same thing last night. 

@lnug/organisers: I have not had any any talk proposals and the meetup page has had minimal response...   so if I'm going to call it off for this week. 

Let's try and have an organiser's call this week to arrange and plan a good online LNUG

**Comment by admataz** [comment]
if anyone thinks differently - let it be known!

**Comment by phazonoverload** [comment]
Understood. Can you add me to the org group so I can get updates? 

Cheers

**Comment by admataz** [comment]
> Understood. Can you add me to the org group so I can get updates?
sure - sorry I thought you were already on the list

**Comment by Ankcorn** [comment]
Hey all, sorry I have not been around to help at all this month.

I would love an organiser's call, great idea.

Also, I noticed that next 4th Wednesday (27th of May) is 11 years from the day of the initial release of node.js 

Maybe we could use that to try and attract some speakers.

Hope to see you all soon
