### ISSUE TITLE
catch up and planning for LNUG while lockdown lasts

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#42]
@lnug/organisers @lnug/contributors 

I'd like to discuss some ideas about how we can continue to be an ongoing positive, informative and fun part of the lives of London node developers whil the lockdown continues  - and think about going beyond trying to replicate the monthly meetup via streaming talk live events. 

I think it's clear that it will be a while before we can meet again and enjoy the buzz around a big table with open boxes of pizza and a free supply of beer. 😢 

Who's up for an hour call some time next week (w.c. 27th April) where we can all get together and plan some ideas? Mid mornings or lunchtimes work well for me. 

Let me know in the comments - and I'll arrange a call.

**Comment by Ankcorn** [comment]
Hey that is a really good idea, I'd be up for something like that.

Somehow I have ended up with lots of (relatively) meetings in the diary next week. I can easily do any time Tuesday, Thursday, Friday. But Monday and Wednesday can only do afternoons.

**Comment by phazonoverload** [comment]
Tuesday and Friday out for me. Others good

**Comment by admataz** [comment]
I've sent out a meeting invitation to contact@lnug.org for 11am-12pm on ~Wednesday~ Thursday  - if you're not on that list - please do join at https://meet.google.com/azy-scff-uym

**Comment by admataz** [comment]
I meant Thursday - sorry

**Comment by Ankcorn** [comment]
Thanks! :)

**Comment by phazonoverload** [comment]
I’ll be there

**Comment by hewIngram** [comment]
Looks like I have refinement + a 1:1 then - If I can shuffle I'll be there if not can someone take some notes and I can catch up?

**Comment by admataz** [comment]
Thanks @hewIngram  - I think we're all reasonably flexible tomorrow - what time could you make it?  I only have a standup to attend at 2:30pm - otherwise open.

Anyone else? @simonmcmanus @seanmtracey @trevorah @clarkie ?

**Comment by phazonoverload** [comment]
I’m busy 10-11, 2-3 and 4-5 tomorrow, FYI. A day out I don’t think we should shift times - but let’s not make decisions in the call itself and take good notes

**Comment by admataz** [comment]
ok thanks @phazonoverload  - sorry to assume your open calendar! Let's go ahead with whoever can join us at 11am and we can take it from there.

**Comment by trevorah** [comment]
I wont be able to stay for the full call today at 11am, but I'll be there at the start. It will be great to see your faces again!

**Comment by admataz** [comment]
# LNUG organisers meeting notes

Thanks to all  who could make it - that was a useful chat.  Here’s my summary - feel free to add thoughts and anything I missed.

Thanks for attending: 
@trevorah @simonmcmanus @phazonoverload @Ankcorn @admataz 

Apologies received: 
@hewIngram 

I’ve added some TODO’s inline with my notes below - and where I think appropriate added an owner - but feel free to amend. 

If anyone wants to discuss more via chat or call - let me know in the comments. 

## hosting and video platforms discusison
@phazonoverload  gave us an unstructured brain dump of the thoughts and observations he has from running a few online events over the last while. 

There are a number of ways to run the online event.  We all agree it’s good to have an event that brings people together  - as opposed to a slow release of recorded material. 

### Talks can be prerecorded - this has some advantages: 
- technically easier to manage and safer from a content production point of view
- speakers are available to field questions live during the talk via chat - we have observed things like [**Svelte Society conference**](https://sveltesociety.dev), adds to the quality of engagement
- lowers stress

### but there are also disadvantages; 
- doubles the time required for the speaker’s involvement
- speakers need to produce/edit  video themselves 

Platforms like [**Vito**](https://vito.community) are emerging that offer a “live tv show“ kind of feel - Vito is expensive - can offer a hybrid of prerecorded and live. 

Kevin can offer [2 options via Vonage](https://www.nexmo.com/blog/2020/04/08/supporting-communities-to-go-online)  - 

- **Remo** - an emulation of a live event via video - all talks  - allows attendees to be promoted to speaker - this could suit our community engagement during an event. Also has breakout rooms for chats between attendees. 
- **Social Café** - we used this at the last online meetup for the breakout rooms after the talks 

### Takeaway/ next steps: 
**Remo** sounds like a great option and we decided we should take up Kevin’s offer to run this for us.  To be confirmed in the coming weeks as we plan the next event (27th May). If it looks like pre-recorded talks are more likely and better option - we should opt for the streamed event with **social cafe**

#### Questions about Remo: (@phazonoverload)
- [x] are there tech requirements for attendees or speakers? 
- [x] are there signup requirements? Do we need to coordinate this with attendee registration? 
- [ ] what adjustments should we make to our normal online media (website, youtube, meetup page)

************

## getting speakers and talk proposals under lockdown
The problem with April’s event was we had no talk proposals - and there was no content for the event. 

We largely rely on speakers coming forward and proposing talks  - but it seems under lockdown it’s more difficult. 

- are people fatigued with zoom calls ?
- is giving an online talk a less attractive prospect for potential speakers? (talking to yourself)

We need to make this easier for speakers - and as ever encourage newness and diversity in our speakers - how can we break down the barriers. 

 - are prepared prerecorded talks easier for the speakers? 
 - will people get lost in self editing? 
 
### Takeaway/ next steps
As organisers, we should lead the way, and if necessary, run an event with only us speaking - show how we think it can be done as a remote event. 

- [ ] each organiser to open a full talk proposal on the speakers repos for discussion.  (@lnug/organisers)


## The next LNUG: 27th May: 11 Years of node.js. 
as pointed out by @thomas this is the 11th Birthday (to the day) of the initial commit to node. [Release v0.0.1 · nodejs/node-v0.x-archive · GitHub](https://github.com/nodejs/node-v0.x-archive/releases/tag/v0.0.1)

Let’s do something to commemorate this - or at least make this a hook/theme for the online meetup on 11 May

- [x] Start a planning issue (@admataz) DONE: https://github.com/lnug/event-planning/issues/43
- [x] Put together a promotional outline for this themed meetup - something we can tweet about and add to the Meetup page/ our website (@Ankcorn)
- [ ] prepare at least one talk with a review of 11 years of node.js (@hewingram?)
- [x] invite some node core speakers (James Snel or Matteo Collina from nearform?  others?)
- [ ] maybe an invitation to community to hashtag send birthday greetings that will be compiled and shared as part of the meetup (video/image)?  


## keeping the conversation going during the month
This is a perennial issue identified before lockdown - I’ve always been keen to promote the idea of ongoing chat and not only have the meetings. I think this is more prevalent now than it was before lockdown. 

We have several (too many?) channels for community: 
- feedback on github
- meetup messages
- twitter
- gitter
- an email address: contact@lnug.org

We have [Gitter](https://gitter.im/lnug) for chat - but why is it so quiet in our channels? 

Should we consider a move to something like **Slack** or **Discord** - i.e. is the problem the platform? do people not want yet another app to manage for their community chatter? 

Or is the problem we don’t actually say anything there? 

My suspicion is that it’s a combination - we are not active, so there’s little chatter or conversation - but gitter doesn’t have the same foothold as Discord or Slack. 

irc? 🤔

### Takeaway/action
We agreed that we will give gitter another go - (or does anyone feel strongly _against_ gitter?) 

- [ ] archive the feedback repos on github and consolidate any community repos into one (@admataz)
- [x] add a permanent notice on meetup and our webpage and twitter profile pointing people to gitter (@admataz)
- [ ] regular effort as organisers to try and bootstrap conversations  - a “hello” every day or two and asking what people are up to. (@lnug/organisers)
- [ ] advertise the gitter channel and rooms more via tweets etc. (@lnug/organisers)
- [x] clarify the [permissions issue](https://github.com/lnug/event-planning/issues/40#issuecomment-603990249) raised by @seanmtracey see: https://gitlab.com/gitlab-org/gitter/webapp/-/blob/develop/docs/oauth-scopes.md#github - which I think answers his concerns
- [ ] let’s revive our neglected newsletter (@admataz)

## LNUG Podcast
[Pilot is out](http://podcast.lnug.org) - we haven’t done much to promote it - but let’s take the technical learnings and move on

Next episode of the **LNUG podcast** is in proposal/concept stage - maybe interview a recruiter about finding work in the lockdown

### Actions
- [ ] find a good interviewee or panel for the recruitment discussion (@simonmcmanus)
- [ ] Contribute to the podcast repos with ideas (@lnug/organisers)
- [ ] If you’re considering being part of the recording, see if you can source a decent microphone. !  LNUG owns one of [these](https://www.amazon.co.uk/TONOR-Professional-Condenser-Microphone-Computer/dp/B01142EPO4/ref=pd_ybh_a_158?_encoding=UTF8&psc=1&refRID=MA20Z1MJCSX5PSGFZVSK) which is not great, but the equivalent would be cheap i think. I did some tests after we recorded the podcast  where I noticed the difference in quality  between me and Simon, and I wish I’d used it. 

## Simon’s hot tips extended
Everyone likes this idea, and it was always popular at meetups (thanks @simonleggsays). Let’s take the idea behind Simon’s hot tips further - and get some user generated content via hashtag going - as an ongoing community-led activity. 

- [ ] put some definition to this idea (@admataz)
- [ ]  let’s start with each @lnug/organiser making a quick video tip and posting it. 


## Closing thoughts: 

### LNUG sponsorship and community in the time of LNUG

How can we engage sponsors and the corporate side of our community  now that our activities are online  - specifically **nearform**,  **pusher**, and our former hosts? 

We spoke about vonage being the role of our “hosts”  -  but what about other new services we need
- live captioning for talks 
- hosting podcast costs
- hosting other services?

### The role of LNUG in people’s lives
We also spoke about how our activities, directly or indirectly are part of people’s livelihoods - how do we continue to have this community benefit at the core of our activities?

Many of us have found our work through LNUG activities
Many of our contributors are not node developers, think of Alex and the video producers who’s mainstay of work from meetups will have vanished, think of our pizza guy, etc. Not suggesting we can answer the world’s problems, but let’s keep community at our core. 
Thanks again, as ever for your contributions

**Comment by phazonoverload** [comment]
Remo:

- Speaker tech requirements: essentially it’s just a video call, so a modern browser
- Registration requirements: you can just provide a link to attendees. They have to provide a name and email (Remo requirement, not Vonage, nor do we do anything with it), but that’s it

**Comment by orliesaurus** [comment]
Great notes

**Comment by phazonoverload** [comment]
I've requested use of Remo with the team. I'll let you know when I hear back - should only be a few days :)

**Comment by phazonoverload** [comment]
All good and approved on our end! I'll reach out with more steps on the event planning card shortly

**Comment by admataz** [comment]
Thanks - nice organising everyone
