### ISSUE TITLE
LNUG #94. 11 years to the day... happy birthday node.js

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#43]
On 27th May, the day for this meetup - it will been exactly 11 years since [Ryan Dahl made the first commit to node.js](https://github.com/nodejs/node-v0.x-archive/releases/tag/v0.0.1) 

This month we are going to review and explore what has happened since. 

Add your talk proposals to https://github.com/lnug/speakers and tag this issue.

**Comment by Ankcorn** [comment]
🍰 We all should have cake!

I am going to reach out to speakers at https://jsvidcon.com/schedule/ If I think there talk would be good for this and see if they would like to submit a talk.

A couple of ones that look node core specific are 

* Writing A CPU Intensive Node.js Server With Worker Threads API

* Dissecting Node.js – How it Works Under the Hood

**Comment by admataz** [comment]
Thanks @Ankcorn  - that looks good. 

Update from me: 
- I've reached out internally at Nearform - there is some interest from at least one core contributor, and others to give talks - will confirm these when I have more detail
- we have [a talk proposal from Aris](https://github.com/lnug/speakers/issues/190)  - looks good to me
- @phazonoverload  has confirmed the video arrangements for the 27th 
- I've  manually updated lnug.org with some details of our May 27th event - will add the details to meetup too.

**Comment by admataz** [comment]
details of the event are now live on [lnug.org](https://lnug.org) and the meetup page. 

@lnug/organisers  - please get the word out!

**Comment by hewIngram** [comment]
This is awesome - thanks all! I've been totally unhelpful sorry! But I'll be around tomrrow and can help with anything that's needed.

**Comment by admataz** [comment]
Thanks everyone for your help last week  - I think it went well. Videos are here: [May 2020 - YouTube](https://www.youtube.com/playlist?list=PLam_80-FY3vRe8-rRVUs7TLqSDMwpdJG9) 
 
Feedback discussion post event: https://github.com/lnug/feedback/issues/117
