### ISSUE TITLE
LNUG #95  - 24th June 2020

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#44]
@lnug/organisers, @lnug/contributors 

We are getting ready for our next meetup  - we have a talk confirmed and another potential. 

- [x] @phazonoverload - would you be able to help with hosting on 24th June? 
- [x] confirm speakers
- [x] update meetup page
- [x] update website
- [x] announce on twitter
- [ ] newsletter update
- [ ] community offers and announcements
- [ ] MC?

**Comment by phazonoverload** [comment]
All good for June 24 😃 Will assume same timings/requirements.

**Comment by phazonoverload** [comment]
It's time to schedule in the same platform overview for team + speakers. Let's confirm the time between organisers and then share the time with speakers. 

I am free pretty much all of Monday/Tuesday, so I'll suggest Tuesday at 2pm BST unless there's an aversion to this? I say we set a time and then, if it doesn't work for anyone, I can pick up with them directly for a 1:1. 

Once we confirm a time I will share the rehearsal link with organisers and you can share with speakers in a calendar invite 😄 

Sound ok @admataz?

**Comment by admataz** [comment]
Thanks @phazonoverload  - Tuesday 2pm is fine with me - I will check with the speakers

**Comment by phazonoverload** [comment]
Link for this meet-up on Wednesday: https://live.remo.co/e/lnug-meetup-june

**Comment by admataz** [comment]
@lnug/organisers  - who's going to be joining us tonight? can you give us a 👋  in the Gitter channel when you arrive and keep an eye on the ongoing chats in Remo

See you later!
