### ISSUE TITLE
Return of the Jedi?

### ISSUE THREAD

**Issue by overlookmotel** [lnug/event-planning#45]
With the world (well UK anyway) awaking from its slumbers, I wonder if any plans afoot to start doing in person meet-ups again?

My personal view is that the summer and early autumn will likely be pretty free of Covid and restrictions, though who knows what will happen in winter. If the worst does happen and we end up locked up again in the winter months, I think it'd be really nice to have some in real life meetups while we can. Make hay while the sun shines...

Personally, being an old fart who's been lucky enough to be jabbed, I'd now be willing to recommence such exciting activities as entering buildings and interacting with other humans. I imagine others may feel similarly and so there may be demand.

Hell, I'll even be the first to jump in an offer to do a talk about my own experimental lockdown project [Livepack](https://github.com/overlookmotel/livepack) if that's of interest.

In short, I miss you guys...

**Comment by Ankcorn** [comment]
Hey! 👋

Hope you are well. We haven't discussed anything yet. We did vaguely attempt to get a discord going as a discussion room for lnug members https://discord.gg/pQfVmeRS its still quite quiet but if we get some momentum going it could be fun

Thank you so much for offering to do a talk. Livepack seems insanely interesting really looking forward to hearing about it.

In terms of events, I think the government advice as it stands says not before the 21st of June.

We would also need to find a willing host. 

We could start planning for a 28th of July return as that gives some wiggle room and safety for circumstances to change.

The other potentially rogue idea I had was to do some kind of outside event, thoughts?

Thanks for reaching out! It is really motivating when people are excited to get out there again and give talks 🥳

**Comment by overlookmotel** [comment]
You mean outside as in outdoors? As it happens you are talking to exactly the right man. For 10 years I ran an outdoor cinema, so I know a certain amount about this, and still have all the gear - screens, projectors etc.

However... I'm afraid to say I don't think it's viable to have presentations if it's outdoors in height of summer. It's impossible to get a visible picture on a screen until after sunset using projection. So you'd either have to not have presentations (probably not viable), or start after sunset (9:30pm or so, probably too late for a lot of people), or get a big LED screen from somewhere (very expensive).

I suppose a wacky way of doing it is everyone brings laptop and you stream the speaker's screen over WiFi, so everyone sees his screen on their own screen.

All that said, I'd bet my bottom dollar that by July the vast majority of people will be willing to go indoors if a venue can be found. How about merging the pre-pub and pub segments into one and do it all in a pub? Lots of pubs have function rooms with screens which can be hired for no cost, in return for the pub keeping the bar take. No free beer or pizza, but it might be easier to organise.

**Comment by arakno** [comment]
Hi all, I'm glad the UK is finally waking up!
Unfortunately, the same impact cannot be felt in Ireland - where I  moved last year.

Anyways, just commenting on this " It's impossible to get a visible picture on a screen until after sunset using projection" @overlookmotel - thought you would like to know more about lusoscreen 
https://www.lusoscreen.com/en/p-ag.htm

I am not endorsing anything here,  i have seen it live and maybe you  find this interesting too

**Comment by Ankcorn** [comment]
Haha it's good when my mad ideas can be tempered by someone with experience. Glad to know it would be challenging

https://www.cityprideclerkenwell.co.uk/ I have been to some meetups in this pub @overlookmotel. What do you think? The pizza is really good so I think it would keep all its LNUG charm.

**Comment by admataz** [comment]
hey all - I'm cleaning up old issues and discussions on LNUG and closing old discussion like this one.  this sounded good at the time - and I think we are refreshing our efforts again - hopefully see you all soon
