### ISSUE TITLE
LNUG summer/autumn in person meetup 

### ISSUE THREAD

**Issue by lyndseysc** [lnug/event-planning#46]
Hi 👋

I'm Lyndsey, I am a senior software engineer working at Beamery, a HR/Talent tech scale-up in London. I work with JS/TS/React/Node. In the past, I have been a speaker at ReactJS Girls London and am generally involved with the dev community on the teaching side with organisations like Code First Girls - have taught the intro to web dev course for 2 years. 

I am looking to help arrange a first in-person LNUG meet-up and to become an organiser of the group in general. I attended my first (and last) LNUG in Feb 2020 when we hosted it in our office. I found meet-ups like LNUG + ReactJS Girls a really great way to meet people and learn when I first arrived in London, but COVID put an abrupt stop to that and remote ones are just not the same. Would love to see JS community meet-ups in London revived (whilst still allowing hybrid streaming options for those who can't be there in person). 

**Details of my proposed meet-up:**

**Venue:** Beamery are moving to a new office in the [Hylo Building](https://hylo-london.com/) near Moorgate in July - we have a dedicated event space with a capacity of about 80-100. Have lots of support to host meetups from engineering dept, I should be able to get some budget for food/drinks. 

**Date:** TBC depending on speakers. Ideally September 2022 would give a decent amount of time for speaker submissions.

**Speakers:** TBC. Would do an open call for general interest Node talks. I spoke to [ Beth Griggs](https://twitter.com/BethGriggs_) already at CityJS conf who is excellent - she said she would be interesting in speaking. I would love to do an event with a combo of 1-2 longer talks (~20 mins) and 1-2 lightning talks (5-10 mins) - keeps it nice and accessible for first time speakers.  

Any Q's let me know.

**Comment by Ankcorn** [comment]
Hey! 👋 

Thank you so much for kicking off the discussion about re starting LNUG. This is so long overdue.

I have a sent out a tweet to see if we can drum up some assistance in organising the event.

One interesting source of speakers could be look through the back catalogue https://www.youtube.com/c/LNUGTeam/videos to see if we can find anyone who would like to speak again.

The venue looks amazing :)

**Comment by lyndseysc** [comment]
👉 submit talks [here](https://github.com/lnug/speakers) !

**Comment by admataz** [comment]
Hooray! 🎉 we are getting back!

Hi @lyndseysc and hello @Ankcorn !!  - it's been a long time!

Thanks @lyndseysc  for kicking this off.  I'm really glad people are coming forward to revive our in-person events. Personally, up to now I've not had the confidence to move forward with in person LNUG events - and  especially having just been through covid myself (having avoided it for 2-years), the 10 days of isolation and associated brain fog hasn't encouraged me - so it's nice to have some feeling more confident... 

A couple things spring to mind immediately: 

Regarding the process and planning - let's find some time to meet-up/zoom call between us and help support this.

Initially, rather than a google form -  I would be keen to maintain our [existing talk proposal process](https://github.com/lnug/speakers) - the discussions and transparency around talk proposals as GitHub have been very useful and always well received by speakers. (Happy to chat about differences)

Let's also chat with @simonmcmanus  about the website - and ways to get that updated.  Up to now this has been an automated process from the GitHub issues in speakers repos on a regular monthly  - but I think there's some scope for improvement here. 

Let's add issues to this repos as we go... I'll meanwhile make more of a habit of checking the discord channel and keeping the conversation going...

**Comment by Ankcorn** [comment]
Hey @admataz it has been way too long.

I had covid not too long ago too, the brain fogg was horrible for me too. Took about 3 weeks to feel normal again. I would not be opposed to mask/social distancing guidelines but I know these are a controversial topic.

Agreed, when I first got involved I found it really helpful to look through the existing talk submissions to build up some confidence in submitting mine. The github issues format works really well.

**Comment by lyndseysc** [comment]
thanks @admataz !! sorry to hear about your covid experience - really keen to keep this as a hybrid to make sure people who can't or aren't able to come in-person for whatever reason aren't excluded. 


updated the comment for talk submission :)

**Comment by Ankcorn** [comment]
keen to keep the momentum up, shall we have a chat on zoom this week. I'm super busy the first half of this week but should be more relaxed thursday and friday. Any times on those days that suit?

**Comment by lyndseysc** [comment]
Hey Thomas - great idea - Thursday would work well with me :)

**Comment by simonmcmanus** [comment]
Hi @lyndseys,  thanks for getting things started again.  let me know if you need any help getting the website back up and running. I'm also happy to do a podcast in the run up or from the event.

**Comment by admataz** [comment]
Hi all! sorry I've been off the grid - I had to duck back to the southern hemisphere to look after some urgent care requirements for my parents. I will try join a meeting when it happens - please let me know when...

**Comment by lyndseysc** [comment]
hey @Ankcorn, no responses on Discord to join the call -  still good to go ahead and have a catchup this or next week?

**Comment by Ankcorn** [comment]
Apologies I went a bit off grid on holiday :) Lets do it, I'm free when ever pretty much, happy to work around everyone.

**Comment by lyndseysc** [comment]
Hey @Ankcorn 👋 
apologies - holiday + catching COVID so I was equally off grid for most of June. Was waiting to see if there would be any submitted talks we could discuss, but noone yet :( 

shall we have a call anyway, and see if we can try and rustle up some speakers in a different way?

**Comment by Ankcorn** [comment]
Good to hear from you, I hope you are feeling better and covid was not too rough. I have some ideas for speakers. I will send out some DM's. I can do any evening or lunchtime this week for a call :)

**Comment by lyndseysc** [comment]
Amazing, let's do thursday evening!

**Comment by Ankcorn** [comment]
Is 5.30pm too early?

**Comment by lyndseysc** [comment]
sweet! if you send me your email (can send on discord if you don't want to post publicly) will send a google meet invite :)

**Comment by admataz** [comment]
hi @lyndseysc  - can you invite me too? adam@admataz.com

**Comment by lyndseysc** [comment]
sent an invite to both ✌️

**Comment by Ankcorn** [comment]
thomasankcorn@gmail.com! Thank you

**Comment by lyndseysc** [comment]
Hey guys! Just following up on the speaker reach outs. Did you have any luck?

Also Beamery want to have a call just to go over the event space details and to get some info on expected attendee numbers, previous events etc. Would either/both of you be free for a 30 min meeting the week of 29th August for this?

**Comment by admataz** [comment]
Hi @lyndseysc - sure - I can have a call next week to discuss. Afternoons are generally better for me...

**Comment by connorlurring** [comment]
Hey folks, great to see this getting going again. Having not attended a LNUG meetup in-person, I was wondering what the target number of talks (or length of time covered by talks) for a meetup is. I'm keen to submit a talk, I just need to choose a topic!

If I can be helpful in any way organising or running the meetup, please let me know.

**Comment by lyndseysc** [comment]
Hey Connor, delighted to hear that 🥳 We are looking for ~2 speakers for this meetup. 
You can submit a talk here https://github.com/lnug/speakers - all the details are in the README :)
