### ISSUE TITLE
LNUG #96 - 9th November 2022 - we're back!

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#47]
Here's our old event checklist, dusted off and pasted in. 

As before - edit as necessary - and add your name to a task. 

## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github
- [ ] Who will emcee this month? 
- [x] Registration - this is all on Meetup now
- [ ] Website updates 
- [x] videographer? 
- [ ] Monthly Mailer (Mailchimp)
- [ ] confirm sponsorship arrangements
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [ ] Confirm with Speakers 
- [ ] Confirm Venue arrangements with Hosts (Beamery this month)
- [ ] Confirm Video 
- [ ] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [ ] Pizza orders
- [ ] Beer orders

## On the Night
- [ ] MC/host
- [ ] --- any special announements or ticket giveaways ---
- [ ] Ticket Scan/ Door  - we need an LNUG member at security
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] ~T-Shirts~ (we ran out a long time ago - another task to get more designed/printed one day)
- [ ] Owner Twitter and tweeting through the evening from LNUGorg account (speak to @admataz about access)
- [ ] Owner to Keep chat discussion rolling on Discuss
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [ ] thanks to speakers
- [ ] thanks to sponsors
- [ ] Stickers 
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [ ] Get video from videographer and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month

Anything else?

**Comment by Ankcorn** [comment]
Hey @lyndseysc, would you be interested in MCing? Happy to talk you through it and help with the slides

**Comment by Ankcorn** [comment]
I can do ticket and door on the night, also happy to do website updates and the mailer :) I don't have access to mail chimp though @admataz

**Comment by lyndseysc** [comment]
happy to MC :) we should have some volunteers from Beamery to help out at the door with you too!

**Comment by admataz** [comment]
Hi @Ankcorn  - seems Mailchimp have changed their terms and no longer allow multiple seats on the free account :(  So I can't add you directly.  

I will message you separately with the owner login

I see Boris' abstract is in - I can update the website now - I have it open here anyway

**Comment by lyndseysc** [comment]
Hey both, two weeks to go!
I think all under control on our side.
I can send out email reminders to the people who have signed up to remind at two weeks/one week mark.
I think we are sitting at about 75 on the event atm. Can we do some more drumming up on the LNUG twitter? I will reach out to any other communities to cross-post it too.

**Comment by lyndseysc** [comment]
Hey @admataz @Ankcorn , someone on the meetup has just mentioned that there is rail strikes on the 9th, which could cause a big problem :( 
Beamery have suggested moving to the 10th or week after. Thoughts? Would have to check with both speakers.

**Comment by lyndseysc** [comment]
There's tube strikes on the 10th too. I think it's looking best if we can delay it a different week

**Comment by admataz** [comment]
Hey @lyndseysc - that is unfortunate. I'm happy to move it if we can get agreement from the speakers

**Comment by admataz** [comment]
@lyndseysc  - can you confirm some potential dates from Beamery? I'm happy to discuss this with the speakers and put out an announcement. @Ankcorn  - any thoughts?

**Comment by Ankcorn** [comment]
I'm pretty flexible 😊 happy to move it whenever.

**Comment by lyndseysc** [comment]
Okay, the dates Beamery can do:

- Tuesday 22nd Nov 
- 6th or 7th December

I will reach out to Simon to check availabilty, could you do the same for Boris @Ankcorn ? And let me know what you both think is best.

What a shame at the last minute 😓

**Comment by Ankcorn** [comment]
Boris can do the December dates,

My worry is that it is sneaking into work Christmas party season, I know my works Christmas party is in the 7th. We might find that limits the success of the event

**Comment by lyndseysc** [comment]
I had similar concerns... 😓 
is the 22nd a no from him?

**Comment by lyndseysc** [comment]
^ just a bump on this q @Ankcorn . Simon can do both, but 22nd would save us from xmas party season.

**Comment by admataz** [comment]
Hi @Ankcorn and @lyndseysc  - personally not keen to move it to December for the same reasons. If it's a choice - I think I'd take my chances sticking with the rail strike day - given we are still getting signups for that day anyway (tubes are affected, but will be running). But if this is impossible from a Beamery perspective, we will obviously have to move it.

**Comment by admataz** [comment]
I think 22nd would be good if Boris can make it.

**Comment by Ankcorn** [comment]
Confirmed Boris can do the 22nd

🎉

**Comment by lyndseysc** [comment]
Woo! Will send an email out with change of date :)

**Comment by Ankcorn** [comment]
We also need to update the website and socials

I can do twitter, @admataz can you show me how to update the website? (would be good to get a little tour)

**Comment by admataz** [comment]
Hey @Ankcorn  - happy to provide a tour - and it's a good chance to share this... will let you make the update. 

Essentially - anything merged to the `main` branch in https://github.com/lnug/website/ will be built and deployed to the netlify hosted site. 

It's all [11ty](https://www.11ty.dev) powered  - and I've kindof made it up as I went -  there's lots of scope for improvement.    

I made use of the [data](https://www.11ty.dev/docs/data/) capabilities.  To update/add an event so it's loaded to the home page you can update the YAML header data for files  in https://github.com/lnug/website/blob/main/src/events/

In this case it should simply be editing  https://github.com/lnug/website/blob/main/src/events/2022-11-lnug-returns.md

Let me know if you want to chat and talk it through or want to make a PR to discuss - or if you don't find the time - I'm happy to do it!

**Comment by Ankcorn** [comment]
Nice I should have time to do that this evening, if I run into an issue I will message you

**Comment by admataz** [comment]
@lyndseysc - we are nearing 150 signups - which is the current limit in the meeting set up... any thoughts from Beamery on increasing capacity? In the past we get a lot of signups on the week before the event.

**Comment by lyndseysc** [comment]
unfortunately a no for fire safety / capacity reasons :( 
 I don't think meetup has any sort of waiting list unless I am missing it? 
Will also send out a 1 week email next week and remind people to RSVP no if they aren't going, which might free up some space!

**Comment by admataz** [comment]
Ok. Thanks. Meetup will switch to a waiting list when capacity is full.

**Comment by Ankcorn** [comment]
This event was so awesome! Thank you for having us @lyndseysc
