### ISSUE TITLE
LNUG #72 - April 2018

### ISSUE THREAD

**Issue by admataz** [lnug/event-planning#7]
Hello @lnug/organisers and @lnug/contributors 

April's meetup is shaping up with a couple of good talks for the 25th. And  this is the month we have plans to try out a new venue this month with Conde Nast. 

Here is the checklist for this month - please choose a task  - some of these will be covered by the new arrangements with the venue. 

Please have a read if the docs at https://github.com/lnug/event-planning  - and ask here in the comments if you have any ideas or questions. 

# Checklist (pick a task!)
## Pre Event
- [x] Find/ confirm speakers! and add them as contributors to github 
- [ ] Who will emcee this month? 
- [ ] Registration - this is all on Meetup now  
- [x] Website updates
- [x] Monthly Mailer (Mailchimp)
- [x] confirm sponsorship arrangements  
- [ ] Slides (usually the MC)

## Last day checks (Monday before event)
- [x] Confirm with Speakers  @admataz
- [x] Confirm Venue arrangements with Makers (or other venue if we ever move)  @admataz
- [x] Confirm Video with Pusher  @admataz
- [x] Mailing Reminder [send out a reminder to anyone who can't make it to cancel and free up places]
- [x] Pizza orders  @admataz
- [x] Beer orders  @admataz
- [ ]  Send attendees list to Michelle @ Conde Nast

## On the Night
- [ ] MC/host  @admataz
- [ ] --- any special announcements or ticket giveaways --- ? 
  - [ ] amsterdam js ticket raffle and discount
  - [ ] nodeconf eu rfp
  - [ ] friday hack day
- [ ] Ticket Scan/ Door 
- [ ] Doors after 7pm - leave a contact number on a note
- [ ] ~T-Shirts~ (we've run out! - need to get more printed!)
- [ ] Twitter and tweeting
- [ ] Keep Gitter discussion rolling
- [ ] Speakers & AV 
- [ ] Receive Pizza   
- [ ] Food & Drink Area Maintenance (keep the cold beer rolling!) 

## After the event
- [x] thanks to speakers
- [x] thanks to sponsors
- [ ] activate next month's registration on Meetup
- [ ] Update the website for next month (if we have speakers)
- [x] Get video  from Pusher and upload to YouTube
- [ ] add those interested in joining lnug orgs
- [ ] duplicate this list for next month

Anything else?

**Comment by leggsimon** [comment]
I'm curious, has it been well communicated that there is a venue change this month? It's been hosted at MA for the best part of 2 years right? I'd be worried that if it isn't well communicated then we might get some people just naturally turn up at MA.

**Comment by admataz** [comment]
thanks @leggsimon. you are right.  it hasn’t been communicated and maybe we should add an extra task here to make a big deal of the venue change and some extra tweets and mentions in the newsletter. that said, the new venue arrangements aren’t actually finalised - i should get some clarity in th next day on a few of the questions i had about conde nast’s requirements and we can take it from there.

**Comment by orliesaurus** [comment]
What conde nast's address?
Can someone create the meetup on meetup.com?

**Comment by admataz** [comment]
Hi @orliesaurus  - I'm back from holiday today and busy doing that right now - will update here when it's done

**Comment by orliesaurus** [comment]
@admataz - cool glad you're back!
I think I found the conde nast address:
1-11 John Adam St, WC2N 6HT

Re the event:
Did Michelle answer your important email? I was reading the thread, and it seems like we need an answer before movin forward

Speak soon !!

**Comment by orliesaurus** [comment]
and one mroe thing, I see two talks for March, one is defo happening, one is a reschedule attempt and one is from an out of town person - do we need a third talk/do we have a third talk?

**Comment by admataz** [comment]
@orliesaurus  - yes I just posted Michelle's reply to the thread. I think we're good to go with the venue change (I've not had objections). There are a couple practicalities to sort out. 

Regarding the lineup - I'm trying to swap the speakers to accommodate an out of town speaker. We are trying a shift to 2 speakers (this was discussed when we met as organisers in January) - it's happened a few times that the 3rd speaker at meetups has been short changed and rushed because we need to finish off and the audience is dwindling anyway - and I want to avoid that. I got feedback from last month's speakers that echoed that.

**Comment by orliesaurus** [comment]
gotcha! i didnt know that haha thanks for sharing

**Comment by dscape** [comment]
@orliesaurus It's called the Adelphi building. You will need to provide names for security, so I recommend you add everyone that might attend to simplify your life and probably designate someone to be downstairs! Hope this helps

**Comment by admataz** [comment]
Thanks @dscape  - yes we need full names for the door - and we are trying to keep the hassle around security to a minimum, Michelle from Condé Nast has agreed to help with keeping this smooth as possible and we will have someone downstairs with security till the talks start to ensure people can get in.

**Comment by FabioAntunes** [comment]
There's an option on meetup, whenever someone rsvp's we can ask for their full name. @admataz do people usually just show on the venue, or do they also rsvp?

**Comment by admataz** [comment]
Thanks @FabioAntunes - on the whole people RSVP when they are coming - but we've been fairly relaxed about checking people in on the door at Makers. 

And yes - we actually already use that extra field to ask people for their github handle if they want to join as contributors - but we have repurposed it for this month to be full name.

**Comment by clarkie** [comment]
I'm away on holiday for the next couple of weeks so I'm going to miss this months event but as I'm just chilling, coding and surfing in Portugal I'm happy to help with remote logistics if helpful?

**Comment by admataz** [comment]
@clarkie sounds amazing 🏄 - I'm just back from a sun and sand and beach holiday taking the kids to their grandparents and I've hit the ground running now that I'm back in London. Will let you know if there's anything you can do to help - thanks!

**Comment by orliesaurus** [comment]
@dscape good heads up, let's hope everything goes smoothly, I was simply asking because I think we should let people know in advance via email!

**Comment by admataz** [comment]
@lnug/contributors - please let me know who's coming to the meetup to help on Wednesday? 

Everything looks good to go.

Remember - we are at a new venue - please be sure you are on the meetup attendees list (let me know if you're not - we need you name on the door)

The new venue is:
Conde Nast
Adelphi Building, 1-10 John Adam St Level 9 · London
The nearest Tube stations are Embankment and Charing Cross

I will be there from about 6pm to get things set up. If you arrive before me please ask for Michelle Garret. 

See you there!

**Comment by leggsimon** [comment]
I'll be there if you need a hand?

**Comment by claudiamatosa** [comment]
^ me too

**Comment by claireinez** [comment]
I'll be there but only after 6.30. I'm so excited for the new venue!

**Comment by elischutze** [comment]
I'm still out of town, bummed to be missing the new venue! Take lots of pics

**Comment by FabioAntunes** [comment]
I will be there.

**Comment by admataz** [comment]
Thanks @leggsimon @claudiamatosa @claireinez @FabioAntunes  - that's great - see you later! It being a new venue, I'm not sure how things will shape up - but if you can be on hand to help things run smoothly. 

@elischutze :( see you next month

**Comment by MattJLeach** [comment]
Hi @admataz I'll be there as well tonight. Would it be possible to send a reminder to update RSVP if people can't go as I have a friend on the waitlist who really wants to attend for the first time?

**Comment by admataz** [comment]
hi @MattJLeach  - I sent a reminder to attendees earlier this morning - how far down the list is your friend?

**Comment by orliesaurus** [comment]
Another good event ! good job everybody! 🙀

**Comment by admataz** [comment]
Thanks all for your contributions last week - get involved for this month on 23rd May: https://github.com/lnug/event-planning/issues/8
