### ISSUE TITLE
Ticket giveaways

### ISSUE THREAD

**Issue by claireinez** [lnug/event-planning#9]
We've often been given free tickets to events and conferences to distribute to our attendees. Usually we do some sort of twitter competition but one of the recent competitions had poor numbers (I think there were three entries for two tickets, and one was from a recruiter) -- this might have had something to do with us asking for a pun and people didn't feel comfortable about it.

Last night it was awesome to offer *diversity* scholarships (https://github.com/lnug/event-planning/issues/8#issuecomment-390906435)! I know we often have free tickets but people really appreciated the fact that this time they were aimed at underrepresented groups. Obviously it won't always be the case that we are specifically given diversity tickets, but perhaps **we should consider prioritising minority demographics in our ticket giveaways in future**? It's a small but impactful way we can help improve the diversity problem in tech.

In any case, I propose a different system for putting oneself forward for the ticket(s): **anyone who is interested approaches the emcee and puts their name "in the hat" for a random draw** at the end of the night. More tweets does lead to better marketing for us but it's difficult to know if those people are specifically interested in the tickets or even available on the date in question, so this way is less ambiguous.

**Comment by admataz** [comment]
I've added this to the guideline docs
